#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriGasolModel;

namespace AriGasolModel	
{
	public partial class AriGasolContext : OpenAccessContext, IAriGasolContextUnitOfWork
	{
		private static string connectionStringName = @"ArigasolConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntityDiagrams1.rlinq");
		
		public AriGasolContext()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public AriGasolContext(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public AriGasolContext(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public AriGasolContext(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public AriGasolContext(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Ssocio> Ssocios 
		{
			get
			{
				return this.GetAll<Ssocio>();
			}
		}
		
		public IQueryable<Sempre> Sempres 
		{
			get
			{
				return this.GetAll<Sempre>();
			}
		}
		
		public IQueryable<Sartic> Sartics 
		{
			get
			{
				return this.GetAll<Sartic>();
			}
		}
		
		public IQueryable<Schfac> Schfacs 
		{
			get
			{
				return this.GetAll<Schfac>();
			}
		}
		
		public IQueryable<Slhfac> Slhfacs 
		{
			get
			{
				return this.GetAll<Slhfac>();
			}
		}
		
		public IQueryable<Starje> Starjes 
		{
			get
			{
				return this.GetAll<Starje>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "mysql";
			backend.ProviderName = "MySql.Data.MySqlClient";
			return backend;
		}
	}
	
	public interface IAriGasolContextUnitOfWork : IUnitOfWork
	{
		IQueryable<Ssocio> Ssocios
		{
			get;
		}
		IQueryable<Sempre> Sempres
		{
			get;
		}
		IQueryable<Sartic> Sartics
		{
			get;
		}
		IQueryable<Schfac> Schfacs
		{
			get;
		}
		IQueryable<Slhfac> Slhfacs
		{
			get;
		}
		IQueryable<Starje> Starjes
		{
			get;
		}
	}
}
#pragma warning restore 1591
