#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriGasolModel;

namespace AriGasolModel	
{
	public partial class Sartic
	{
		private int _codartic;
		public virtual int Codartic
		{
			get
			{
				return this._codartic;
			}
			set
			{
				this._codartic = value;
			}
		}
		
		private string _nomartic;
		public virtual string Nomartic
		{
			get
			{
				return this._nomartic;
			}
			set
			{
				this._nomartic = value;
			}
		}
		
		private short _codfamia;
		public virtual short Codfamia
		{
			get
			{
				return this._codfamia;
			}
			set
			{
				this._codfamia = value;
			}
		}
		
		private string _codigean;
		public virtual string Codigean
		{
			get
			{
				return this._codigean;
			}
			set
			{
				this._codigean = value;
			}
		}
		
		private short? _numtanqu;
		public virtual short? Numtanqu
		{
			get
			{
				return this._numtanqu;
			}
			set
			{
				this._numtanqu = value;
			}
		}
		
		private short? _nummangu;
		public virtual short? Nummangu
		{
			get
			{
				return this._nummangu;
			}
			set
			{
				this._nummangu = value;
			}
		}
		
		private string _codmacta;
		public virtual string Codmacta
		{
			get
			{
				return this._codmacta;
			}
			set
			{
				this._codmacta = value;
			}
		}
		
		private string _codmaccl;
		public virtual string Codmaccl
		{
			get
			{
				return this._codmaccl;
			}
			set
			{
				this._codmaccl = value;
			}
		}
		
		private short _codigiva;
		public virtual short Codigiva
		{
			get
			{
				return this._codigiva;
			}
			set
			{
				this._codigiva = value;
			}
		}
		
		private decimal _preventa;
		public virtual decimal Preventa
		{
			get
			{
				return this._preventa;
			}
			set
			{
				this._preventa = value;
			}
		}
		
		private decimal _bonigral;
		public virtual decimal Bonigral
		{
			get
			{
				return this._bonigral;
			}
			set
			{
				this._bonigral = value;
			}
		}
		
		private decimal _canstock;
		public virtual decimal Canstock
		{
			get
			{
				return this._canstock;
			}
			set
			{
				this._canstock = value;
			}
		}
		
		private decimal? _stockinv;
		public virtual decimal? Stockinv
		{
			get
			{
				return this._stockinv;
			}
			set
			{
				this._stockinv = value;
			}
		}
		
		private DateTime? _fechainv;
		public virtual DateTime? Fechainv
		{
			get
			{
				return this._fechainv;
			}
			set
			{
				this._fechainv = value;
			}
		}
		
		private decimal? _preciopmp;
		public virtual decimal? Preciopmp
		{
			get
			{
				return this._preciopmp;
			}
			set
			{
				this._preciopmp = value;
			}
		}
		
		private decimal? _ultpreci;
		public virtual decimal? Ultpreci
		{
			get
			{
				return this._ultpreci;
			}
			set
			{
				this._ultpreci = value;
			}
		}
		
		private DateTime? _ultfecha;
		public virtual DateTime? Ultfecha
		{
			get
			{
				return this._ultfecha;
			}
			set
			{
				this._ultfecha = value;
			}
		}
		
		private decimal? _impuesto;
		public virtual decimal? Impuesto
		{
			get
			{
				return this._impuesto;
			}
			set
			{
				this._impuesto = value;
			}
		}
		
		private short _tipogaso;
		public virtual short Tipogaso
		{
			get
			{
				return this._tipogaso;
			}
			set
			{
				this._tipogaso = value;
			}
		}
		
		private short _gp;
		public virtual short Gp
		{
			get
			{
				return this._gp;
			}
			set
			{
				this._gp = value;
			}
		}
		
		private decimal _porcbd;
		public virtual decimal Porcbd
		{
			get
			{
				return this._porcbd;
			}
			set
			{
				this._porcbd = value;
			}
		}
		
		private int? _artdto;
		public virtual int? Artdto
		{
			get
			{
				return this._artdto;
			}
			set
			{
				this._artdto = value;
			}
		}
		
		private short _ctrstock;
		public virtual short Ctrstock
		{
			get
			{
				return this._ctrstock;
			}
			set
			{
				this._ctrstock = value;
			}
		}
		
		private string _ctacompr;
		public virtual string Ctacompr
		{
			get
			{
				return this._ctacompr;
			}
			set
			{
				this._ctacompr = value;
			}
		}
		
		private short? _artnuevo;
		public virtual short? Artnuevo
		{
			get
			{
				return this._artnuevo;
			}
			set
			{
				this._artnuevo = value;
			}
		}
		
		private decimal? _pesoart;
		public virtual decimal? Pesoart
		{
			get
			{
				return this._pesoart;
			}
			set
			{
				this._pesoart = value;
			}
		}
		
		private decimal? _precsigaus;
		public virtual decimal? Precsigaus
		{
			get
			{
				return this._precsigaus;
			}
			set
			{
				this._precsigaus = value;
			}
		}
		
		private Sartic _sartic1;
		public virtual Sartic Sartic1
		{
			get
			{
				return this._sartic1;
			}
			set
			{
				this._sartic1 = value;
			}
		}
		
		private IList<Sartic> _sartics = new List<Sartic>();
		public virtual IList<Sartic> Sartics
		{
			get
			{
				return this._sartics;
			}
		}
		
		private IList<Slhfac> _slhfacs = new List<Slhfac>();
		public virtual IList<Slhfac> Slhfacs
		{
			get
			{
				return this._slhfacs;
			}
		}
		
	}
}
#pragma warning restore 1591
