#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriGasolModel;

namespace AriGasolModel	
{
	public partial class Slhfac
	{
		private string _letraser;
		public virtual string Letraser
		{
			get
			{
				return this._letraser;
			}
			set
			{
				this._letraser = value;
			}
		}
		
		private int _numfactu;
		public virtual int Numfactu
		{
			get
			{
				return this._numfactu;
			}
			set
			{
				this._numfactu = value;
			}
		}
		
		private DateTime _fecfactu;
		public virtual DateTime Fecfactu
		{
			get
			{
				return this._fecfactu;
			}
			set
			{
				this._fecfactu = value;
			}
		}
		
		private short _numlinea;
		public virtual short Numlinea
		{
			get
			{
				return this._numlinea;
			}
			set
			{
				this._numlinea = value;
			}
		}
		
		private string _numalbar;
		public virtual string Numalbar
		{
			get
			{
				return this._numalbar;
			}
			set
			{
				this._numalbar = value;
			}
		}
		
		private DateTime _fecalbar;
		public virtual DateTime Fecalbar
		{
			get
			{
				return this._fecalbar;
			}
			set
			{
				this._fecalbar = value;
			}
		}
		
		private DateTime _horalbar;
		public virtual DateTime Horalbar
		{
			get
			{
				return this._horalbar;
			}
			set
			{
				this._horalbar = value;
			}
		}
		
		private short _codturno;
		public virtual short Codturno
		{
			get
			{
				return this._codturno;
			}
			set
			{
				this._codturno = value;
			}
		}
		
		private int _numtarje;
		public virtual int Numtarje
		{
			get
			{
				return this._numtarje;
			}
			set
			{
				this._numtarje = value;
			}
		}
		
		private int _codartic;
		public virtual int Codartic
		{
			get
			{
				return this._codartic;
			}
			set
			{
				this._codartic = value;
			}
		}
		
		private decimal _cantidad;
		public virtual decimal Cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				this._cantidad = value;
			}
		}
		
		private decimal _preciove;
		public virtual decimal Preciove
		{
			get
			{
				return this._preciove;
			}
			set
			{
				this._preciove = value;
			}
		}
		
		private decimal _implinea;
		public virtual decimal Implinea
		{
			get
			{
				return this._implinea;
			}
			set
			{
				this._implinea = value;
			}
		}
		
		private string _matricul;
		public virtual string Matricul
		{
			get
			{
				return this._matricul;
			}
			set
			{
				this._matricul = value;
			}
		}
		
		private decimal? _precioinicial;
		public virtual decimal? Precioinicial
		{
			get
			{
				return this._precioinicial;
			}
			set
			{
				this._precioinicial = value;
			}
		}
		
		private Sartic _sartic;
		public virtual Sartic Sartic
		{
			get
			{
				return this._sartic;
			}
			set
			{
				this._sartic = value;
			}
		}
		
		private Schfac _schfac;
		public virtual Schfac Schfac
		{
			get
			{
				return this._schfac;
			}
			set
			{
				this._schfac = value;
			}
		}
		
	}
}
#pragma warning restore 1591
