#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriGasolModel;

namespace AriGasolModel	
{
	public partial class Ssocio
	{
		private int _codsocio;
		public virtual int Codsocio
		{
			get
			{
				return this._codsocio;
			}
			set
			{
				this._codsocio = value;
			}
		}
		
		private short _codcoope;
		public virtual short Codcoope
		{
			get
			{
				return this._codcoope;
			}
			set
			{
				this._codcoope = value;
			}
		}
		
		private string _nomsocio;
		public virtual string Nomsocio
		{
			get
			{
				return this._nomsocio;
			}
			set
			{
				this._nomsocio = value;
			}
		}
		
		private string _domsocio;
		public virtual string Domsocio
		{
			get
			{
				return this._domsocio;
			}
			set
			{
				this._domsocio = value;
			}
		}
		
		private string _codposta;
		public virtual string Codposta
		{
			get
			{
				return this._codposta;
			}
			set
			{
				this._codposta = value;
			}
		}
		
		private string _pobsocio;
		public virtual string Pobsocio
		{
			get
			{
				return this._pobsocio;
			}
			set
			{
				this._pobsocio = value;
			}
		}
		
		private string _prosocio;
		public virtual string Prosocio
		{
			get
			{
				return this._prosocio;
			}
			set
			{
				this._prosocio = value;
			}
		}
		
		private string _nifsocio;
		public virtual string Nifsocio
		{
			get
			{
				return this._nifsocio;
			}
			set
			{
				this._nifsocio = value;
			}
		}
		
		private string _telsocio;
		public virtual string Telsocio
		{
			get
			{
				return this._telsocio;
			}
			set
			{
				this._telsocio = value;
			}
		}
		
		private string _faxsocio;
		public virtual string Faxsocio
		{
			get
			{
				return this._faxsocio;
			}
			set
			{
				this._faxsocio = value;
			}
		}
		
		private string _movsocio;
		public virtual string Movsocio
		{
			get
			{
				return this._movsocio;
			}
			set
			{
				this._movsocio = value;
			}
		}
		
		private string _maisocio;
		public virtual string Maisocio
		{
			get
			{
				return this._maisocio;
			}
			set
			{
				this._maisocio = value;
			}
		}
		
		private string _wwwsocio;
		public virtual string Wwwsocio
		{
			get
			{
				return this._wwwsocio;
			}
			set
			{
				this._wwwsocio = value;
			}
		}
		
		private DateTime _fechaalt;
		public virtual DateTime Fechaalt
		{
			get
			{
				return this._fechaalt;
			}
			set
			{
				this._fechaalt = value;
			}
		}
		
		private DateTime? _fechabaj;
		public virtual DateTime? Fechabaj
		{
			get
			{
				return this._fechabaj;
			}
			set
			{
				this._fechabaj = value;
			}
		}
		
		private short _codtarif;
		public virtual short Codtarif
		{
			get
			{
				return this._codtarif;
			}
			set
			{
				this._codtarif = value;
			}
		}
		
		private string _codbanco;
		public virtual string Codbanco
		{
			get
			{
				return this._codbanco;
			}
			set
			{
				this._codbanco = value;
			}
		}
		
		private string _codsucur;
		public virtual string Codsucur
		{
			get
			{
				return this._codsucur;
			}
			set
			{
				this._codsucur = value;
			}
		}
		
		private string _digcontr;
		public virtual string Digcontr
		{
			get
			{
				return this._digcontr;
			}
			set
			{
				this._digcontr = value;
			}
		}
		
		private string _cuentaba;
		public virtual string Cuentaba
		{
			get
			{
				return this._cuentaba;
			}
			set
			{
				this._cuentaba = value;
			}
		}
		
		private short _impfactu;
		public virtual short Impfactu
		{
			get
			{
				return this._impfactu;
			}
			set
			{
				this._impfactu = value;
			}
		}
		
		private decimal _dtolitro;
		public virtual decimal Dtolitro
		{
			get
			{
				return this._dtolitro;
			}
			set
			{
				this._dtolitro = value;
			}
		}
		
		private short _codforpa;
		public virtual short Codforpa
		{
			get
			{
				return this._codforpa;
			}
			set
			{
				this._codforpa = value;
			}
		}
		
		private byte _tipsocio;
		public virtual byte Tipsocio
		{
			get
			{
				return this._tipsocio;
			}
			set
			{
				this._tipsocio = value;
			}
		}
		
		private short _bonifbas;
		public virtual short Bonifbas
		{
			get
			{
				return this._bonifbas;
			}
			set
			{
				this._bonifbas = value;
			}
		}
		
		private short _bonifesp;
		public virtual short Bonifesp
		{
			get
			{
				return this._bonifesp;
			}
			set
			{
				this._bonifesp = value;
			}
		}
		
		private short _codsitua;
		public virtual short Codsitua
		{
			get
			{
				return this._codsitua;
			}
			set
			{
				this._codsitua = value;
			}
		}
		
		private string _codmacta;
		public virtual string Codmacta
		{
			get
			{
				return this._codmacta;
			}
			set
			{
				this._codmacta = value;
			}
		}
		
		private string _obssocio;
		public virtual string Obssocio
		{
			get
			{
				return this._obssocio;
			}
			set
			{
				this._obssocio = value;
			}
		}
		
		private short _grupoestartic;
		public virtual short Grupoestartic
		{
			get
			{
				return this._grupoestartic;
			}
			set
			{
				this._grupoestartic = value;
			}
		}
		
		private short _facturafp;
		public virtual short Facturafp
		{
			get
			{
				return this._facturafp;
			}
			set
			{
				this._facturafp = value;
			}
		}
		
		private int? _nrosocio;
		public virtual int? Nrosocio
		{
			get
			{
				return this._nrosocio;
			}
			set
			{
				this._nrosocio = value;
			}
		}
		
		private short _envfactemail;
		public virtual short Envfactemail
		{
			get
			{
				return this._envfactemail;
			}
			set
			{
				this._envfactemail = value;
			}
		}
		
		private IList<Schfac> _schfacs = new List<Schfac>();
		public virtual IList<Schfac> Schfacs
		{
			get
			{
				return this._schfacs;
			}
		}
		
	}
}
#pragma warning restore 1591
