#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriGasolModel;

namespace AriGasolModel	
{
	public partial class Starje
	{
		private int _codsocio;
		public virtual int Codsocio
		{
			get
			{
				return this._codsocio;
			}
			set
			{
				this._codsocio = value;
			}
		}
		
		private int _numlinea;
		public virtual int Numlinea
		{
			get
			{
				return this._numlinea;
			}
			set
			{
				this._numlinea = value;
			}
		}
		
		private int _numtarje;
		public virtual int Numtarje
		{
			get
			{
				return this._numtarje;
			}
			set
			{
				this._numtarje = value;
			}
		}
		
		private string _organoGestor;
		public virtual string OrganoGestor
		{
			get
			{
				return this._organoGestor;
			}
			set
			{
				this._organoGestor = value;
			}
		}
		
		private string _unidadTramitadora;
		public virtual string UnidadTramitadora
		{
			get
			{
				return this._unidadTramitadora;
			}
			set
			{
				this._unidadTramitadora = value;
			}
		}
		
		private string _oficinaContable;
		public virtual string OficinaContable
		{
			get
			{
				return this._oficinaContable;
			}
			set
			{
				this._oficinaContable = value;
			}
		}
		
		private string _organoProponente;
		public virtual string OrganoProponente
		{
			get
			{
				return this._organoProponente;
			}
			set
			{
				this._organoProponente = value;
			}
		}
		
		private IList<Slhfac> _slhfacs = new List<Slhfac>();
		public virtual IList<Slhfac> Slhfacs
		{
			get
			{
				return this._slhfacs;
			}
		}
		
	}
}
#pragma warning restore 1591
