#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriFacElec;

namespace AriFacElec	
{
	public partial class Sartic
	{
		private short unicajas;
		public virtual short Unicajas
		{
			get
			{
				return this.unicajas;
			}
			set
			{
				this.unicajas = value;
			}
		}
		
		private DateTime? ultfecpvp;
		public virtual DateTime? Ultfecpvp
		{
			get
			{
				return this.ultfecpvp;
			}
			set
			{
				this.ultfecpvp = value;
			}
		}
		
		private DateTime? ultfecco;
		public virtual DateTime? Ultfecco
		{
			get
			{
				return this.ultfecco;
			}
			set
			{
				this.ultfecco = value;
			}
		}
		
		private string txtauxdocumento;
		public virtual string Txtauxdocumento
		{
			get
			{
				return this.txtauxdocumento;
			}
			set
			{
				this.txtauxdocumento = value;
			}
		}
		
		private string textoven;
		public virtual string Textoven
		{
			get
			{
				return this.textoven;
			}
			set
			{
				this.textoven = value;
			}
		}
		
		private string textocom;
		public virtual string Textocom
		{
			get
			{
				return this.textocom;
			}
			set
			{
				this.textocom = value;
			}
		}
		
		private decimal preciove;
		public virtual decimal Preciove
		{
			get
			{
				return this.preciove;
			}
			set
			{
				this.preciove = value;
			}
		}
		
		private decimal? preciouc;
		public virtual decimal? Preciouc
		{
			get
			{
				return this.preciouc;
			}
			set
			{
				this.preciouc = value;
			}
		}
		
		private decimal? preciost;
		public virtual decimal? Preciost
		{
			get
			{
				return this.preciost;
			}
			set
			{
				this.preciost = value;
			}
		}
		
		private decimal? preciomp;
		public virtual decimal? Preciomp
		{
			get
			{
				return this.preciomp;
			}
			set
			{
				this.preciomp = value;
			}
		}
		
		private decimal? precioma;
		public virtual decimal? Precioma
		{
			get
			{
				return this.precioma;
			}
			set
			{
				this.precioma = value;
			}
		}
		
		private decimal? preanuman;
		public virtual decimal? Preanuman
		{
			get
			{
				return this.preanuman;
			}
			set
			{
				this.preanuman = value;
			}
		}
		
		private decimal? pesoarti;
		public virtual decimal? Pesoarti
		{
			get
			{
				return this.pesoarti;
			}
			set
			{
				this.pesoarti = value;
			}
		}
		
		private string numserie;
		public virtual string Numserie
		{
			get
			{
				return this.numserie;
			}
			set
			{
				this.numserie = value;
			}
		}
		
		private int numorden;
		public virtual int Numorden
		{
			get
			{
				return this.numorden;
			}
			set
			{
				this.numorden = value;
			}
		}
		
		private byte nseriesn;
		public virtual byte Nseriesn
		{
			get
			{
				return this.nseriesn;
			}
			set
			{
				this.nseriesn = value;
			}
		}
		
		private string nomartic;
		public virtual string Nomartic
		{
			get
			{
				return this.nomartic;
			}
			set
			{
				this.nomartic = value;
			}
		}
		
		private byte mateprima;
		public virtual byte Mateprima
		{
			get
			{
				return this.mateprima;
			}
			set
			{
				this.mateprima = value;
			}
		}
		
		private decimal? margecom;
		public virtual decimal? Margecom
		{
			get
			{
				return this.margecom;
			}
			set
			{
				this.margecom = value;
			}
		}
		
		private short garantia;
		public virtual short Garantia
		{
			get
			{
				return this.garantia;
			}
			set
			{
				this.garantia = value;
			}
		}
		
		private DateTime? fecvigen;
		public virtual DateTime? Fecvigen
		{
			get
			{
				return this.fecvigen;
			}
			set
			{
				this.fecvigen = value;
			}
		}
		
		private DateTime fecaltas;
		public virtual DateTime Fecaltas
		{
			get
			{
				return this.fecaltas;
			}
			set
			{
				this.fecaltas = value;
			}
		}
		
		private byte ctrstock;
		public virtual byte Ctrstock
		{
			get
			{
				return this.ctrstock;
			}
			set
			{
				this.ctrstock = value;
			}
		}
		
		private string controli;
		public virtual string Controli
		{
			get
			{
				return this.controli;
			}
			set
			{
				this.controli = value;
			}
		}
		
		private byte conjunto;
		public virtual byte Conjunto
		{
			get
			{
				return this.conjunto;
			}
			set
			{
				this.conjunto = value;
			}
		}
		
		private short codunida;
		public virtual short Codunida
		{
			get
			{
				return this.codunida;
			}
			set
			{
				this.codunida = value;
			}
		}
		
		private string codtipar;
		public virtual string Codtipar
		{
			get
			{
				return this.codtipar;
			}
			set
			{
				this.codtipar = value;
			}
		}
		
		private string codtelem;
		public virtual string Codtelem
		{
			get
			{
				return this.codtelem;
			}
			set
			{
				this.codtelem = value;
			}
		}
		
		private short codstatu;
		public virtual short Codstatu
		{
			get
			{
				return this.codstatu;
			}
			set
			{
				this.codstatu = value;
			}
		}
		
		private int codprove;
		public virtual int Codprove
		{
			get
			{
				return this.codprove;
			}
			set
			{
				this.codprove = value;
			}
		}
		
		private short codmarca;
		public virtual short Codmarca
		{
			get
			{
				return this.codmarca;
			}
			set
			{
				this.codmarca = value;
			}
		}
		
		private byte codigiva;
		public virtual byte Codigiva
		{
			get
			{
				return this.codigiva;
			}
			set
			{
				this.codigiva = value;
			}
		}
		
		private short codfamia;
		public virtual short Codfamia
		{
			get
			{
				return this.codfamia;
			}
			set
			{
				this.codfamia = value;
			}
		}
		
		private string codcateg;
		public virtual string Codcateg
		{
			get
			{
				return this.codcateg;
			}
			set
			{
				this.codcateg = value;
			}
		}
		
		private string codartic;
		public virtual string Codartic
		{
			get
			{
				return this.codartic;
			}
			set
			{
				this.codartic = value;
			}
		}
		
		private short artvario;
		public virtual short Artvario
		{
			get
			{
				return this.artvario;
			}
			set
			{
				this.artvario = value;
			}
		}
		
		private decimal? litrosUnidad;
		public virtual decimal? LitrosUnidad
		{
			get
			{
				return this.litrosUnidad;
			}
			set
			{
				this.litrosUnidad = value;
			}
		}
		
		private IList<Slifac> slifacs = new List<Slifac>();
		public virtual IList<Slifac> Slifacs
		{
			get
			{
				return this.slifacs;
			}
		}
		
	}
}
#pragma warning restore 1591
