#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriFacElec;

namespace AriFacElec	
{
	public partial class Scafac1
	{
		private string codtipom;
		public virtual string Codtipom
		{
			get
			{
				return this.codtipom;
			}
			set
			{
				this.codtipom = value;
			}
		}
		
		private int numfactu;
		public virtual int Numfactu
		{
			get
			{
				return this.numfactu;
			}
			set
			{
				this.numfactu = value;
			}
		}
		
		private DateTime fecfactu;
		public virtual DateTime Fecfactu
		{
			get
			{
				return this.fecfactu;
			}
			set
			{
				this.fecfactu = value;
			}
		}
		
		private string codtipoa;
		public virtual string Codtipoa
		{
			get
			{
				return this.codtipoa;
			}
			set
			{
				this.codtipoa = value;
			}
		}
		
		private int numalbar;
		public virtual int Numalbar
		{
			get
			{
				return this.numalbar;
			}
			set
			{
				this.numalbar = value;
			}
		}
		
		private string referenc;
		public virtual string Referenc
		{
			get
			{
				return this.referenc;
			}
			set
			{
				this.referenc = value;
			}
		}
		
		private string refpedido;
		public virtual string Refpedido
		{
			get
			{
				return this.refpedido;
			}
			set
			{
				this.refpedido = value;
			}
		}
		
		private string refcontrato;
		public virtual string Refcontrato
		{
			get
			{
				return this.refcontrato;
			}
			set
			{
				this.refcontrato = value;
			}
		}
		
		private IList<Slifac> slifacs = new List<Slifac>();
		public virtual IList<Slifac> Slifacs
		{
			get
			{
				return this.slifacs;
			}
		}
		
	}
}
#pragma warning restore 1591
