#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriFacElec;

namespace AriFacElec	
{
	public partial class Sclien
	{
		private int codclien;
		public virtual int Codclien
		{
			get
			{
				return this.codclien;
			}
			set
			{
				this.codclien = value;
			}
		}
		
		private string nomclien;
		public virtual string Nomclien
		{
			get
			{
				return this.nomclien;
			}
			set
			{
				this.nomclien = value;
			}
		}
		
		private string nomcomer;
		public virtual string Nomcomer
		{
			get
			{
				return this.nomcomer;
			}
			set
			{
				this.nomcomer = value;
			}
		}
		
		private string domclien;
		public virtual string Domclien
		{
			get
			{
				return this.domclien;
			}
			set
			{
				this.domclien = value;
			}
		}
		
		private string codpobla;
		public virtual string Codpobla
		{
			get
			{
				return this.codpobla;
			}
			set
			{
				this.codpobla = value;
			}
		}
		
		private string pobclien;
		public virtual string Pobclien
		{
			get
			{
				return this.pobclien;
			}
			set
			{
				this.pobclien = value;
			}
		}
		
		private string proclien;
		public virtual string Proclien
		{
			get
			{
				return this.proclien;
			}
			set
			{
				this.proclien = value;
			}
		}
		
		private string nifclien;
		public virtual string Nifclien
		{
			get
			{
				return this.nifclien;
			}
			set
			{
				this.nifclien = value;
			}
		}
		
		private string wwwclien;
		public virtual string Wwwclien
		{
			get
			{
				return this.wwwclien;
			}
			set
			{
				this.wwwclien = value;
			}
		}
		
		private DateTime? fechamov;
		public virtual DateTime? Fechamov
		{
			get
			{
				return this.fechamov;
			}
			set
			{
				this.fechamov = value;
			}
		}
		
		private DateTime fechaalt;
		public virtual DateTime Fechaalt
		{
			get
			{
				return this.fechaalt;
			}
			set
			{
				this.fechaalt = value;
			}
		}
		
		private short codactiv;
		public virtual short Codactiv
		{
			get
			{
				return this.codactiv;
			}
			set
			{
				this.codactiv = value;
			}
		}
		
		private short? codenvio;
		public virtual short? Codenvio
		{
			get
			{
				return this.codenvio;
			}
			set
			{
				this.codenvio = value;
			}
		}
		
		private short? codzonas;
		public virtual short? Codzonas
		{
			get
			{
				return this.codzonas;
			}
			set
			{
				this.codzonas = value;
			}
		}
		
		private short? codrutas;
		public virtual short? Codrutas
		{
			get
			{
				return this.codrutas;
			}
			set
			{
				this.codrutas = value;
			}
		}
		
		private short codagent;
		public virtual short Codagent
		{
			get
			{
				return this.codagent;
			}
			set
			{
				this.codagent = value;
			}
		}
		
		private short codforpa;
		public virtual short Codforpa
		{
			get
			{
				return this.codforpa;
			}
			set
			{
				this.codforpa = value;
			}
		}
		
		private byte? diapago1;
		public virtual byte? Diapago1
		{
			get
			{
				return this.diapago1;
			}
			set
			{
				this.diapago1 = value;
			}
		}
		
		private byte? diapago2;
		public virtual byte? Diapago2
		{
			get
			{
				return this.diapago2;
			}
			set
			{
				this.diapago2 = value;
			}
		}
		
		private byte? diapago3;
		public virtual byte? Diapago3
		{
			get
			{
				return this.diapago3;
			}
			set
			{
				this.diapago3 = value;
			}
		}
		
		private short? codbanco;
		public virtual short? Codbanco
		{
			get
			{
				return this.codbanco;
			}
			set
			{
				this.codbanco = value;
			}
		}
		
		private short? codsucur;
		public virtual short? Codsucur
		{
			get
			{
				return this.codsucur;
			}
			set
			{
				this.codsucur = value;
			}
		}
		
		private string digcontr;
		public virtual string Digcontr
		{
			get
			{
				return this.digcontr;
			}
			set
			{
				this.digcontr = value;
			}
		}
		
		private string cuentaba;
		public virtual string Cuentaba
		{
			get
			{
				return this.cuentaba;
			}
			set
			{
				this.cuentaba = value;
			}
		}
		
		private string codmacta;
		public virtual string Codmacta
		{
			get
			{
				return this.codmacta;
			}
			set
			{
				this.codmacta = value;
			}
		}
		
		private string perclie1;
		public virtual string Perclie1
		{
			get
			{
				return this.perclie1;
			}
			set
			{
				this.perclie1 = value;
			}
		}
		
		private string telclie1;
		public virtual string Telclie1
		{
			get
			{
				return this.telclie1;
			}
			set
			{
				this.telclie1 = value;
			}
		}
		
		private string faxclie1;
		public virtual string Faxclie1
		{
			get
			{
				return this.faxclie1;
			}
			set
			{
				this.faxclie1 = value;
			}
		}
		
		private string maiclie1;
		public virtual string Maiclie1
		{
			get
			{
				return this.maiclie1;
			}
			set
			{
				this.maiclie1 = value;
			}
		}
		
		private string perclie2;
		public virtual string Perclie2
		{
			get
			{
				return this.perclie2;
			}
			set
			{
				this.perclie2 = value;
			}
		}
		
		private string telclie2;
		public virtual string Telclie2
		{
			get
			{
				return this.telclie2;
			}
			set
			{
				this.telclie2 = value;
			}
		}
		
		private string faxclie2;
		public virtual string Faxclie2
		{
			get
			{
				return this.faxclie2;
			}
			set
			{
				this.faxclie2 = value;
			}
		}
		
		private string maiclie2;
		public virtual string Maiclie2
		{
			get
			{
				return this.maiclie2;
			}
			set
			{
				this.maiclie2 = value;
			}
		}
		
		private byte clivario;
		public virtual byte Clivario
		{
			get
			{
				return this.clivario;
			}
			set
			{
				this.clivario = value;
			}
		}
		
		private byte tipoiva;
		public virtual byte Tipoiva
		{
			get
			{
				return this.tipoiva;
			}
			set
			{
				this.tipoiva = value;
			}
		}
		
		private byte tipofact;
		public virtual byte Tipofact
		{
			get
			{
				return this.tipofact;
			}
			set
			{
				this.tipofact = value;
			}
		}
		
		private byte albarcon;
		public virtual byte Albarcon
		{
			get
			{
				return this.albarcon;
			}
			set
			{
				this.albarcon = value;
			}
		}
		
		private byte periodof;
		public virtual byte Periodof
		{
			get
			{
				return this.periodof;
			}
			set
			{
				this.periodof = value;
			}
		}
		
		private byte? numrepet;
		public virtual byte? Numrepet
		{
			get
			{
				return this.numrepet;
			}
			set
			{
				this.numrepet = value;
			}
		}
		
		private byte? mesnogir;
		public virtual byte? Mesnogir
		{
			get
			{
				return this.mesnogir;
			}
			set
			{
				this.mesnogir = value;
			}
		}
		
		private byte? diavtoat;
		public virtual byte? Diavtoat
		{
			get
			{
				return this.diavtoat;
			}
			set
			{
				this.diavtoat = value;
			}
		}
		
		private short codtarif;
		public virtual short Codtarif
		{
			get
			{
				return this.codtarif;
			}
			set
			{
				this.codtarif = value;
			}
		}
		
		private decimal dtoppago;
		public virtual decimal Dtoppago
		{
			get
			{
				return this.dtoppago;
			}
			set
			{
				this.dtoppago = value;
			}
		}
		
		private decimal dtognral;
		public virtual decimal Dtognral
		{
			get
			{
				return this.dtognral;
			}
			set
			{
				this.dtognral = value;
			}
		}
		
		private byte promocio;
		public virtual byte Promocio
		{
			get
			{
				return this.promocio;
			}
			set
			{
				this.promocio = value;
			}
		}
		
		private short codsitua;
		public virtual short Codsitua
		{
			get
			{
				return this.codsitua;
			}
			set
			{
				this.codsitua = value;
			}
		}
		
		private byte referobl;
		public virtual byte Referobl
		{
			get
			{
				return this.referobl;
			}
			set
			{
				this.referobl = value;
			}
		}
		
		private byte cliabono;
		public virtual byte Cliabono
		{
			get
			{
				return this.cliabono;
			}
			set
			{
				this.cliabono = value;
			}
		}
		
		private short? kilometr;
		public virtual short? Kilometr
		{
			get
			{
				return this.kilometr;
			}
			set
			{
				this.kilometr = value;
			}
		}
		
		private decimal? limcredi;
		public virtual decimal? Limcredi
		{
			get
			{
				return this.limcredi;
			}
			set
			{
				this.limcredi = value;
			}
		}
		
		private DateTime? fechaulr;
		public virtual DateTime? Fechaulr
		{
			get
			{
				return this.fechaulr;
			}
			set
			{
				this.fechaulr = value;
			}
		}
		
		private string pasclien;
		public virtual string Pasclien
		{
			get
			{
				return this.pasclien;
			}
			set
			{
				this.pasclien = value;
			}
		}
		
		private string observac;
		public virtual string Observac
		{
			get
			{
				return this.observac;
			}
			set
			{
				this.observac = value;
			}
		}
		
		private byte tasareciclado;
		public virtual byte Tasareciclado
		{
			get
			{
				return this.tasareciclado;
			}
			set
			{
				this.tasareciclado = value;
			}
		}
		
		private byte? enviocorreo;
		public virtual byte? Enviocorreo
		{
			get
			{
				return this.enviocorreo;
			}
			set
			{
				this.enviocorreo = value;
			}
		}
		
		private IList<Scafac> scafacs = new List<Scafac>();
		public virtual IList<Scafac> Scafacs
		{
			get
			{
				return this.scafacs;
			}
		}
		
	}
}
#pragma warning restore 1591
