#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriFacElec;

namespace AriFacElec	
{
	public partial class Sdirec
	{
		private int codclien;
		public virtual int Codclien
		{
			get
			{
				return this.codclien;
			}
			set
			{
				this.codclien = value;
			}
		}
		
		private short coddirec;
		public virtual short Coddirec
		{
			get
			{
				return this.coddirec;
			}
			set
			{
				this.coddirec = value;
			}
		}
		
		private string nomdirec;
		public virtual string Nomdirec
		{
			get
			{
				return this.nomdirec;
			}
			set
			{
				this.nomdirec = value;
			}
		}
		
		private string domdirec;
		public virtual string Domdirec
		{
			get
			{
				return this.domdirec;
			}
			set
			{
				this.domdirec = value;
			}
		}
		
		private string codpobla;
		public virtual string Codpobla
		{
			get
			{
				return this.codpobla;
			}
			set
			{
				this.codpobla = value;
			}
		}
		
		private string pobdirec;
		public virtual string Pobdirec
		{
			get
			{
				return this.pobdirec;
			}
			set
			{
				this.pobdirec = value;
			}
		}
		
		private string prodirec;
		public virtual string Prodirec
		{
			get
			{
				return this.prodirec;
			}
			set
			{
				this.prodirec = value;
			}
		}
		
		private string perdirec;
		public virtual string Perdirec
		{
			get
			{
				return this.perdirec;
			}
			set
			{
				this.perdirec = value;
			}
		}
		
		private string teldirec;
		public virtual string Teldirec
		{
			get
			{
				return this.teldirec;
			}
			set
			{
				this.teldirec = value;
			}
		}
		
		private string faxdirec;
		public virtual string Faxdirec
		{
			get
			{
				return this.faxdirec;
			}
			set
			{
				this.faxdirec = value;
			}
		}
		
		private string maidirec;
		public virtual string Maidirec
		{
			get
			{
				return this.maidirec;
			}
			set
			{
				this.maidirec = value;
			}
		}
		
		private short codbanco;
		public virtual short Codbanco
		{
			get
			{
				return this.codbanco;
			}
			set
			{
				this.codbanco = value;
			}
		}
		
		private short codsucur;
		public virtual short Codsucur
		{
			get
			{
				return this.codsucur;
			}
			set
			{
				this.codsucur = value;
			}
		}
		
		private string digcontr;
		public virtual string Digcontr
		{
			get
			{
				return this.digcontr;
			}
			set
			{
				this.digcontr = value;
			}
		}
		
		private string cuentaba;
		public virtual string Cuentaba
		{
			get
			{
				return this.cuentaba;
			}
			set
			{
				this.cuentaba = value;
			}
		}
		
		private short codzona;
		public virtual short Codzona
		{
			get
			{
				return this.codzona;
			}
			set
			{
				this.codzona = value;
			}
		}
		
		private string iban;
		public virtual string Iban
		{
			get
			{
				return this.iban;
			}
			set
			{
				this.iban = value;
			}
		}
		
		private string organoGestor;
		public virtual string OrganoGestor
		{
			get
			{
				return this.organoGestor;
			}
			set
			{
				this.organoGestor = value;
			}
		}
		
		private string unidadTramitadora;
		public virtual string UnidadTramitadora
		{
			get
			{
				return this.unidadTramitadora;
			}
			set
			{
				this.unidadTramitadora = value;
			}
		}
		
		private string oficinaContable;
		public virtual string OficinaContable
		{
			get
			{
				return this.oficinaContable;
			}
			set
			{
				this.oficinaContable = value;
			}
		}
		
		private string organoProponente;
		public virtual string OrganoProponente
		{
			get
			{
				return this.organoProponente;
			}
			set
			{
				this.organoProponente = value;
			}
		}
		
		private IList<Scafac> scafacs = new List<Scafac>();
		public virtual IList<Scafac> Scafacs
		{
			get
			{
				return this.scafacs;
			}
		}
		
	}
}
#pragma warning restore 1591
