#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriFacElec;

namespace AriFacElec	
{
	public partial class Slifac
	{
		private decimal? preciouc;
		public virtual decimal? Preciouc
		{
			get
			{
				return this.preciouc;
			}
			set
			{
				this.preciouc = value;
			}
		}
		
		private decimal? preciost;
		public virtual decimal? Preciost
		{
			get
			{
				return this.preciost;
			}
			set
			{
				this.preciost = value;
			}
		}
		
		private decimal? preciomp;
		public virtual decimal? Preciomp
		{
			get
			{
				return this.preciomp;
			}
			set
			{
				this.preciomp = value;
			}
		}
		
		private decimal? precioiv;
		public virtual decimal? Precioiv
		{
			get
			{
				return this.precioiv;
			}
			set
			{
				this.precioiv = value;
			}
		}
		
		private decimal? precioar;
		public virtual decimal? Precioar
		{
			get
			{
				return this.precioar;
			}
			set
			{
				this.precioar = value;
			}
		}
		
		private Char origpre;
		public virtual Char Origpre
		{
			get
			{
				return this.origpre;
			}
			set
			{
				this.origpre = value;
			}
		}
		
		private string numlote;
		public virtual string Numlote
		{
			get
			{
				return this.numlote;
			}
			set
			{
				this.numlote = value;
			}
		}
		
		private short numlinea;
		public virtual short Numlinea
		{
			get
			{
				return this.numlinea;
			}
			set
			{
				this.numlinea = value;
			}
		}
		
		private int numfactu;
		public virtual int Numfactu
		{
			get
			{
				return this.numfactu;
			}
			set
			{
				this.numfactu = value;
			}
		}
		
		private int numbultos;
		public virtual int Numbultos
		{
			get
			{
				return this.numbultos;
			}
			set
			{
				this.numbultos = value;
			}
		}
		
		private int numalbar;
		public virtual int Numalbar
		{
			get
			{
				return this.numalbar;
			}
			set
			{
				this.numalbar = value;
			}
		}
		
		private string nomartic;
		public virtual string Nomartic
		{
			get
			{
				return this.nomartic;
			}
			set
			{
				this.nomartic = value;
			}
		}
		
		private decimal? importel;
		public virtual decimal? Importel
		{
			get
			{
				return this.importel;
			}
			set
			{
				this.importel = value;
			}
		}
		
		private DateTime fecfactu;
		public virtual DateTime Fecfactu
		{
			get
			{
				return this.fecfactu;
			}
			set
			{
				this.fecfactu = value;
			}
		}
		
		private decimal dtoline2;
		public virtual decimal Dtoline2
		{
			get
			{
				return this.dtoline2;
			}
			set
			{
				this.dtoline2 = value;
			}
		}
		
		private decimal dtoline1;
		public virtual decimal Dtoline1
		{
			get
			{
				return this.dtoline1;
			}
			set
			{
				this.dtoline1 = value;
			}
		}
		
		private string codtipom;
		public virtual string Codtipom
		{
			get
			{
				return this.codtipom;
			}
			set
			{
				this.codtipom = value;
			}
		}
		
		private string codtipoa;
		public virtual string Codtipoa
		{
			get
			{
				return this.codtipoa;
			}
			set
			{
				this.codtipoa = value;
			}
		}
		
		private int codproveX;
		public virtual int CodproveX
		{
			get
			{
				return this.codproveX;
			}
			set
			{
				this.codproveX = value;
			}
		}
		
		private string codccost;
		public virtual string Codccost
		{
			get
			{
				return this.codccost;
			}
			set
			{
				this.codccost = value;
			}
		}
		
		private string codartic;
		public virtual string Codartic
		{
			get
			{
				return this.codartic;
			}
			set
			{
				this.codartic = value;
			}
		}
		
		private short codalmac;
		public virtual short Codalmac
		{
			get
			{
				return this.codalmac;
			}
			set
			{
				this.codalmac = value;
			}
		}
		
		private decimal? cantidad;
		public virtual decimal? Cantidad
		{
			get
			{
				return this.cantidad;
			}
			set
			{
				this.cantidad = value;
			}
		}
		
		private string ampliaci;
		public virtual string Ampliaci
		{
			get
			{
				return this.ampliaci;
			}
			set
			{
				this.ampliaci = value;
			}
		}
		
		private Scafac scafac;
		public virtual Scafac Scafac
		{
			get
			{
				return this.scafac;
			}
			set
			{
				this.scafac = value;
			}
		}
		
		private Sartic sartic;
		public virtual Sartic Sartic
		{
			get
			{
				return this.sartic;
			}
			set
			{
				this.sartic = value;
			}
		}
		
	}
}
#pragma warning restore 1591
