#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace AriFacElec	
{
	public partial class Spara1
	{
		private string webversion;
		public virtual string Webversion
		{
			get
			{
				return this.webversion;
			}
			set
			{
				this.webversion = value;
			}
		}
		
		private string websoporte;
		public virtual string Websoporte
		{
			get
			{
				return this.websoporte;
			}
			set
			{
				this.websoporte = value;
			}
		}
		
		private string usuconta;
		public virtual string Usuconta
		{
			get
			{
				return this.usuconta;
			}
			set
			{
				this.usuconta = value;
			}
		}
		
		private byte tipodtos;
		public virtual byte Tipodtos
		{
			get
			{
				return this.tipodtos;
			}
			set
			{
				this.tipodtos = value;
			}
		}
		
		private string smtpuser;
		public virtual string Smtpuser
		{
			get
			{
				return this.smtpuser;
			}
			set
			{
				this.smtpuser = value;
			}
		}
		
		private string smtppass;
		public virtual string Smtppass
		{
			get
			{
				return this.smtppass;
			}
			set
			{
				this.smtppass = value;
			}
		}
		
		private string smtphost;
		public virtual string Smtphost
		{
			get
			{
				return this.smtphost;
			}
			set
			{
				this.smtphost = value;
			}
		}
		
		private string serconta;
		public virtual string Serconta
		{
			get
			{
				return this.serconta;
			}
			set
			{
				this.serconta = value;
			}
		}
		
		private byte? produccion;
		public virtual byte? Produccion
		{
			get
			{
				return this.produccion;
			}
			set
			{
				this.produccion = value;
			}
		}
		
		private decimal? preukmtc;
		public virtual decimal? Preukmtc
		{
			get
			{
				return this.preukmtc;
			}
			set
			{
				this.preukmtc = value;
			}
		}
		
		private decimal? preukmcl;
		public virtual decimal? Preukmcl
		{
			get
			{
				return this.preukmcl;
			}
			set
			{
				this.preukmcl = value;
			}
		}
		
		private decimal? porreten;
		public virtual decimal? Porreten
		{
			get
			{
				return this.porreten;
			}
			set
			{
				this.porreten = value;
			}
		}
		
		private string pasconta;
		public virtual string Pasconta
		{
			get
			{
				return this.pasconta;
			}
			set
			{
				this.pasconta = value;
			}
		}
		
		private byte ordendto;
		public virtual byte Ordendto
		{
			get
			{
				return this.ordendto;
			}
			set
			{
				this.ordendto = value;
			}
		}
		
		private byte? numconta;
		public virtual byte? Numconta
		{
			get
			{
				return this.numconta;
			}
			set
			{
				this.numconta = value;
			}
		}
		
		private string nomgeren;
		public virtual string Nomgeren
		{
			get
			{
				return this.nomgeren;
			}
			set
			{
				this.nomgeren = value;
			}
		}
		
		private string nomadmin;
		public virtual string Nomadmin
		{
			get
			{
				return this.nomadmin;
			}
			set
			{
				this.nomadmin = value;
			}
		}
		
		private byte modanalitica;
		public virtual byte Modanalitica
		{
			get
			{
				return this.modanalitica;
			}
			set
			{
				this.modanalitica = value;
			}
		}
		
		private byte? mesnogir;
		public virtual byte? Mesnogir
		{
			get
			{
				return this.mesnogir;
			}
			set
			{
				this.mesnogir = value;
			}
		}
		
		private string mailsoporte;
		public virtual string Mailsoporte
		{
			get
			{
				return this.mailsoporte;
			}
			set
			{
				this.mailsoporte = value;
			}
		}
		
		private short? ivare3eq;
		public virtual short? Ivare3eq
		{
			get
			{
				return this.ivare3eq;
			}
			set
			{
				this.ivare3eq = value;
			}
		}
		
		private short? ivare3;
		public virtual short? Ivare3
		{
			get
			{
				return this.ivare3;
			}
			set
			{
				this.ivare3 = value;
			}
		}
		
		private short? ivare2eq;
		public virtual short? Ivare2eq
		{
			get
			{
				return this.ivare2eq;
			}
			set
			{
				this.ivare2eq = value;
			}
		}
		
		private short? ivare2;
		public virtual short? Ivare2
		{
			get
			{
				return this.ivare2;
			}
			set
			{
				this.ivare2 = value;
			}
		}
		
		private short? ivare1eq;
		public virtual short? Ivare1eq
		{
			get
			{
				return this.ivare1eq;
			}
			set
			{
				this.ivare1eq = value;
			}
		}
		
		private short? ivare1;
		public virtual short? Ivare1
		{
			get
			{
				return this.ivare1;
			}
			set
			{
				this.ivare1 = value;
			}
		}
		
		private short? ivaexento;
		public virtual short? Ivaexento
		{
			get
			{
				return this.ivaexento;
			}
			set
			{
				this.ivaexento = value;
			}
		}
		
		private short? ivaRea;
		public virtual short? Iva_rea
		{
			get
			{
				return this.ivaRea;
			}
			set
			{
				this.ivaRea = value;
			}
		}
		
		private short? ivaOldre2;
		public virtual short? Iva_oldre2
		{
			get
			{
				return this.ivaOldre2;
			}
			set
			{
				this.ivaOldre2 = value;
			}
		}
		
		private short? ivaOldre1;
		public virtual short? Iva_oldre1
		{
			get
			{
				return this.ivaOldre1;
			}
			set
			{
				this.ivaOldre1 = value;
			}
		}
		
		private short? ivaOld2;
		public virtual short? Iva_old2
		{
			get
			{
				return this.ivaOld2;
			}
			set
			{
				this.ivaOld2 = value;
			}
		}
		
		private short? ivaOld1;
		public virtual short? Iva_old1
		{
			get
			{
				return this.ivaOld1;
			}
			set
			{
				this.ivaOld1 = value;
			}
		}
		
		private byte inventar;
		public virtual byte Inventar
		{
			get
			{
				return this.inventar;
			}
			set
			{
				this.inventar = value;
			}
		}
		
		private decimal? impminped;
		public virtual decimal? Impminped
		{
			get
			{
				return this.impminped;
			}
			set
			{
				this.impminped = value;
			}
		}
		
		private byte hayservicio;
		public virtual byte Hayservicio
		{
			get
			{
				return this.hayservicio;
			}
			set
			{
				this.hayservicio = value;
			}
		}
		
		private byte hayrepar;
		public virtual byte Hayrepar
		{
			get
			{
				return this.hayrepar;
			}
			set
			{
				this.hayrepar = value;
			}
		}
		
		private byte haynserie;
		public virtual byte Haynserie
		{
			get
			{
				return this.haynserie;
			}
			set
			{
				this.haynserie = value;
			}
		}
		
		private byte haymante;
		public virtual byte Haymante
		{
			get
			{
				return this.haymante;
			}
			set
			{
				this.haymante = value;
			}
		}
		
		private byte hayfrecu;
		public virtual byte Hayfrecu
		{
			get
			{
				return this.hayfrecu;
			}
			set
			{
				this.hayfrecu = value;
			}
		}
		
		private byte haydepar;
		public virtual byte Haydepar
		{
			get
			{
				return this.haydepar;
			}
			set
			{
				this.haydepar = value;
			}
		}
		
		private byte dtoxcanti;
		public virtual byte Dtoxcanti
		{
			get
			{
				return this.dtoxcanti;
			}
			set
			{
				this.dtoxcanti = value;
			}
		}
		
		private string diremail;
		public virtual string Diremail
		{
			get
			{
				return this.diremail;
			}
			set
			{
				this.diremail = value;
			}
		}
		
		private short diassiman;
		public virtual short Diassiman
		{
			get
			{
				return this.diassiman;
			}
			set
			{
				this.diassiman = value;
			}
		}
		
		private short diasnoman;
		public virtual short Diasnoman
		{
			get
			{
				return this.diasnoman;
			}
			set
			{
				this.diasnoman = value;
			}
		}
		
		private short? diasgaranrepa;
		public virtual short? Diasgaranrepa
		{
			get
			{
				return this.diasgaranrepa;
			}
			set
			{
				this.diasgaranrepa = value;
			}
		}
		
		private byte? diapago3;
		public virtual byte? Diapago3
		{
			get
			{
				return this.diapago3;
			}
			set
			{
				this.diapago3 = value;
			}
		}
		
		private byte? diapago2;
		public virtual byte? Diapago2
		{
			get
			{
				return this.diapago2;
			}
			set
			{
				this.diapago2 = value;
			}
		}
		
		private byte? diapago1;
		public virtual byte? Diapago1
		{
			get
			{
				return this.diapago1;
			}
			set
			{
				this.diapago1 = value;
			}
		}
		
		private byte? descriptores;
		public virtual byte? Descriptores
		{
			get
			{
				return this.descriptores;
			}
			set
			{
				this.descriptores = value;
			}
		}
		
		private short? defzona;
		public virtual short? Defzona
		{
			get
			{
				return this.defzona;
			}
			set
			{
				this.defzona = value;
			}
		}
		
		private short? deftarifa;
		public virtual short? Deftarifa
		{
			get
			{
				return this.deftarifa;
			}
			set
			{
				this.deftarifa = value;
			}
		}
		
		private short? defstituacion;
		public virtual short? Defstituacion
		{
			get
			{
				return this.defstituacion;
			}
			set
			{
				this.defstituacion = value;
			}
		}
		
		private short? defruta;
		public virtual short? Defruta
		{
			get
			{
				return this.defruta;
			}
			set
			{
				this.defruta = value;
			}
		}
		
		private short? defenvio;
		public virtual short? Defenvio
		{
			get
			{
				return this.defenvio;
			}
			set
			{
				this.defenvio = value;
			}
		}
		
		private short? defagente;
		public virtual short? Defagente
		{
			get
			{
				return this.defagente;
			}
			set
			{
				this.defagente = value;
			}
		}
		
		private short? defactividad;
		public virtual short? Defactividad
		{
			get
			{
				return this.defactividad;
			}
			set
			{
				this.defactividad = value;
			}
		}
		
		private byte ctrstock;
		public virtual byte Ctrstock
		{
			get
			{
				return this.ctrstock;
			}
			set
			{
				this.ctrstock = value;
			}
		}
		
		private string ctareten;
		public virtual string Ctareten
		{
			get
			{
				return this.ctareten;
			}
			set
			{
				this.ctareten = value;
			}
		}
		
		private string ctaaportacion;
		public virtual string Ctaaportacion
		{
			get
			{
				return this.ctaaportacion;
			}
			set
			{
				this.ctaaportacion = value;
			}
		}
		
		private byte creatarifart;
		public virtual byte Creatarifart
		{
			get
			{
				return this.creatarifart;
			}
			set
			{
				this.creatarifart = value;
			}
		}
		
		private short? conttickagrupado;
		public virtual short? Conttickagrupado
		{
			get
			{
				return this.conttickagrupado;
			}
			set
			{
				this.conttickagrupado = value;
			}
		}
		
		private short? contaB;
		public virtual short? Conta_B
		{
			get
			{
				return this.contaB;
			}
			set
			{
				this.contaB = value;
			}
		}
		
		private byte? compoporcen;
		public virtual byte? Compoporcen
		{
			get
			{
				return this.compoporcen;
			}
			set
			{
				this.compoporcen = value;
			}
		}
		
		private short codtarif;
		public virtual short Codtarif
		{
			get
			{
				return this.codtarif;
			}
			set
			{
				this.codtarif = value;
			}
		}
		
		private byte codigo;
		public virtual byte Codigo
		{
			get
			{
				return this.codigo;
			}
			set
			{
				this.codigo = value;
			}
		}
		
		private short? codforpa;
		public virtual short? Codforpa
		{
			get
			{
				return this.codforpa;
			}
			set
			{
				this.codforpa = value;
			}
		}
		
		private string codartid;
		public virtual string Codartid
		{
			get
			{
				return this.codartid;
			}
			set
			{
				this.codartid = value;
			}
		}
		
		private string codartictel;
		public virtual string Codartictel
		{
			get
			{
				return this.codartictel;
			}
			set
			{
				this.codartictel = value;
			}
		}
		
		private byte cajacomp;
		public virtual byte Cajacomp
		{
			get
			{
				return this.cajacomp;
			}
			set
			{
				this.cajacomp = value;
			}
		}
		
		private short? avirepara;
		public virtual short? Avirepara
		{
			get
			{
				return this.avirepara;
			}
			set
			{
				this.avirepara = value;
			}
		}
		
		private short? avipedpro;
		public virtual short? Avipedpro
		{
			get
			{
				return this.avipedpro;
			}
			set
			{
				this.avipedpro = value;
			}
		}
		
		private short? avipedcli;
		public virtual short? Avipedcli
		{
			get
			{
				return this.avipedcli;
			}
			set
			{
				this.avipedcli = value;
			}
		}
		
		private short? avimanteni;
		public virtual short? Avimanteni
		{
			get
			{
				return this.avimanteni;
			}
			set
			{
				this.avimanteni = value;
			}
		}
		
		private short? aviavios;
		public virtual short? Aviavios
		{
			get
			{
				return this.aviavios;
			}
			set
			{
				this.aviavios = value;
			}
		}
		
		private short? avialbpro;
		public virtual short? Avialbpro
		{
			get
			{
				return this.avialbpro;
			}
			set
			{
				this.avialbpro = value;
			}
		}
		
		private short? avialbcli;
		public virtual short? Avialbcli
		{
			get
			{
				return this.avialbcli;
			}
			set
			{
				this.avialbcli = value;
			}
		}
		
		private string arigesmail;
		public virtual string Arigesmail
		{
			get
			{
				return this.arigesmail;
			}
			set
			{
				this.arigesmail = value;
			}
		}
		
		private decimal? abonokilos;
		public virtual decimal? Abonokilos
		{
			get
			{
				return this.abonokilos;
			}
			set
			{
				this.abonokilos = value;
			}
		}
		
		private byte? tieneCRM;
		public virtual byte? TieneCRM
		{
			get
			{
				return this.tieneCRM;
			}
			set
			{
				this.tieneCRM = value;
			}
		}
		
		private byte? obsFactura;
		public virtual byte? ObsFactura
		{
			get
			{
				return this.obsFactura;
			}
			set
			{
				this.obsFactura = value;
			}
		}
		
		private short? numCopias;
		public virtual short? NumCopias
		{
			get
			{
				return this.numCopias;
			}
			set
			{
				this.numCopias = value;
			}
		}
		
		private short? ivaIntracom;
		public virtual short? IvaIntracom
		{
			get
			{
				return this.ivaIntracom;
			}
			set
			{
				this.ivaIntracom = value;
			}
		}
		
		private byte? envioDesdeOutlook;
		public virtual byte? EnvioDesdeOutlook
		{
			get
			{
				return this.envioDesdeOutlook;
			}
			set
			{
				this.envioDesdeOutlook = value;
			}
		}
		
		private string articuloPortes;
		public virtual string ArticuloPortes
		{
			get
			{
				return this.articuloPortes;
			}
			set
			{
				this.articuloPortes = value;
			}
		}
		
		private string artReciclado;
		public virtual string ArtReciclado
		{
			get
			{
				return this.artReciclado;
			}
			set
			{
				this.artReciclado = value;
			}
		}
		
	}
}
#pragma warning restore 1591
