#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace AriFacElec	
{
	public partial class Sparam
	{
		private byte codigo;
		public virtual byte Codigo
		{
			get
			{
				return this.codigo;
			}
			set
			{
				this.codigo = value;
			}
		}
		
		private string nomempre;
		public virtual string Nomempre
		{
			get
			{
				return this.nomempre;
			}
			set
			{
				this.nomempre = value;
			}
		}
		
		private string domempre;
		public virtual string Domempre
		{
			get
			{
				return this.domempre;
			}
			set
			{
				this.domempre = value;
			}
		}
		
		private string codpobla;
		public virtual string Codpobla
		{
			get
			{
				return this.codpobla;
			}
			set
			{
				this.codpobla = value;
			}
		}
		
		private string pobempre;
		public virtual string Pobempre
		{
			get
			{
				return this.pobempre;
			}
			set
			{
				this.pobempre = value;
			}
		}
		
		private string proempre;
		public virtual string Proempre
		{
			get
			{
				return this.proempre;
			}
			set
			{
				this.proempre = value;
			}
		}
		
		private string cifempre;
		public virtual string Cifempre
		{
			get
			{
				return this.cifempre;
			}
			set
			{
				this.cifempre = value;
			}
		}
		
		private string telempre;
		public virtual string Telempre
		{
			get
			{
				return this.telempre;
			}
			set
			{
				this.telempre = value;
			}
		}
		
		private string faxempre;
		public virtual string Faxempre
		{
			get
			{
				return this.faxempre;
			}
			set
			{
				this.faxempre = value;
			}
		}
		
		private string wwwempre;
		public virtual string Wwwempre
		{
			get
			{
				return this.wwwempre;
			}
			set
			{
				this.wwwempre = value;
			}
		}
		
		private string maiempre;
		public virtual string Maiempre
		{
			get
			{
				return this.maiempre;
			}
			set
			{
				this.maiempre = value;
			}
		}
		
	}
}
#pragma warning restore 1591
