#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriFacElec;

namespace AriFacElec	
{
	public partial class Stipom
	{
		private byte? tipodocu;
		public virtual byte? Tipodocu
		{
			get
			{
				return this.tipodocu;
			}
			set
			{
				this.tipodocu = value;
			}
		}
		
		private string nomtipom;
		public virtual string Nomtipom
		{
			get
			{
				return this.nomtipom;
			}
			set
			{
				this.nomtipom = value;
			}
		}
		
		private byte muevesto;
		public virtual byte Muevesto
		{
			get
			{
				return this.muevesto;
			}
			set
			{
				this.muevesto = value;
			}
		}
		
		private string letraser;
		public virtual string Letraser
		{
			get
			{
				return this.letraser;
			}
			set
			{
				this.letraser = value;
			}
		}
		
		private int contador;
		public virtual int Contador
		{
			get
			{
				return this.contador;
			}
			set
			{
				this.contador = value;
			}
		}
		
		private string codtipom;
		public virtual string Codtipom
		{
			get
			{
				return this.codtipom;
			}
			set
			{
				this.codtipom = value;
			}
		}
		
		private IList<Scafac> scafacs = new List<Scafac>();
		public virtual IList<Scafac> Scafacs
		{
			get
			{
				return this.scafacs;
			}
		}
		
	}
}
#pragma warning restore 1591
