#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriFacElec;

namespace AriFacElec	
{
	public partial class Svenci
	{
		private string codtipom;
		public virtual string Codtipom
		{
			get
			{
				return this.codtipom;
			}
			set
			{
				this.codtipom = value;
			}
		}
		
		private int numfactu;
		public virtual int Numfactu
		{
			get
			{
				return this.numfactu;
			}
			set
			{
				this.numfactu = value;
			}
		}
		
		private DateTime fecfactu;
		public virtual DateTime Fecfactu
		{
			get
			{
				return this.fecfactu;
			}
			set
			{
				this.fecfactu = value;
			}
		}
		
		private ushort ordefect;
		public virtual ushort Ordefect
		{
			get
			{
				return this.ordefect;
			}
			set
			{
				this.ordefect = value;
			}
		}
		
		private DateTime fecefect;
		public virtual DateTime Fecefect
		{
			get
			{
				return this.fecefect;
			}
			set
			{
				this.fecefect = value;
			}
		}
		
		private decimal impefect;
		public virtual decimal Impefect
		{
			get
			{
				return this.impefect;
			}
			set
			{
				this.impefect = value;
			}
		}
		
		private Scafac scafac;
		public virtual Scafac Scafac
		{
			get
			{
				return this.scafac;
			}
			set
			{
				this.scafac = value;
			}
		}
		
	}
}
#pragma warning restore 1591
