#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace AriFacElec	
{
	public partial class Tiposiva
	{
		private byte codigiva;
		public virtual byte Codigiva
		{
			get
			{
				return this.codigiva;
			}
			set
			{
				this.codigiva = value;
			}
		}
		
		private string nombriva;
		public virtual string Nombriva
		{
			get
			{
				return this.nombriva;
			}
			set
			{
				this.nombriva = value;
			}
		}
		
		private byte tipodiva;
		public virtual byte Tipodiva
		{
			get
			{
				return this.tipodiva;
			}
			set
			{
				this.tipodiva = value;
			}
		}
		
		private decimal porceiva;
		public virtual decimal Porceiva
		{
			get
			{
				return this.porceiva;
			}
			set
			{
				this.porceiva = value;
			}
		}
		
		private decimal? porcerec;
		public virtual decimal? Porcerec
		{
			get
			{
				return this.porcerec;
			}
			set
			{
				this.porcerec = value;
			}
		}
		
		private string cuentare;
		public virtual string Cuentare
		{
			get
			{
				return this.cuentare;
			}
			set
			{
				this.cuentare = value;
			}
		}
		
		private string cuentarr;
		public virtual string Cuentarr
		{
			get
			{
				return this.cuentarr;
			}
			set
			{
				this.cuentarr = value;
			}
		}
		
		private string cuentaso;
		public virtual string Cuentaso
		{
			get
			{
				return this.cuentaso;
			}
			set
			{
				this.cuentaso = value;
			}
		}
		
		private string cuentasr;
		public virtual string Cuentasr
		{
			get
			{
				return this.cuentasr;
			}
			set
			{
				this.cuentasr = value;
			}
		}
		
		private string cuentasn;
		public virtual string Cuentasn
		{
			get
			{
				return this.cuentasn;
			}
			set
			{
				this.cuentasn = value;
			}
		}
		
	}
}
#pragma warning restore 1591
