#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using FacElecLib;

namespace FacElecLib	
{
	public partial class base_firmada : base_loc
	{
		private int iD;
		public virtual int ID
		{
			get
			{
				return this.iD;
			}
			set
			{
				this.iD = value;
			}
		}
		
		private IList<srv_origen> srvOrigens = new List<srv_origen>();
		public virtual IList<srv_origen> srv_origens
		{
			get
			{
				return this.srvOrigens;
			}
		}
		
	}
}
#pragma warning restore 1591
