#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace FacElecLib	
{
	public partial class base_loc
	{
		protected string server1;
		public virtual string server
		{
			get
			{
				return this.server1;
			}
			set
			{
				this.server1 = value;
			}
		}
		
		protected string userId;
		public virtual string user_id
		{
			get
			{
				return this.userId;
			}
			set
			{
				this.userId = value;
			}
		}
		
		protected string passw1;
		public virtual string passw
		{
			get
			{
				return this.passw1;
			}
			set
			{
				this.passw1 = value;
			}
		}
		
		protected string db1;
		public virtual string db
		{
			get
			{
				return this.db1;
			}
			set
			{
				this.db1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
