#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using FacElecLib;

namespace FacElecLib	
{
	public partial class Fac_elecEntity : OpenAccessContext, IFac_elecEntityUnitOfWork
	{
		private static string connectionStringName = @"Fac_elecEntity";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntityDiagrams.rlinq");
		
		public Fac_elecEntity()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public Fac_elecEntity(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public Fac_elecEntity(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public Fac_elecEntity(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public Fac_elecEntity(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<srv_origen> srv_origens 
		{
			get
			{
				return this.GetAll<srv_origen>();
			}
		}
		
		public IQueryable<base_firmada> base_firmadas 
		{
			get
			{
				return this.GetAll<base_firmada>();
			}
		}
		
		public IQueryable<base_loc> base_locs 
		{
			get
			{
				return this.GetAll<base_loc>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "mysql";
			return backend;
		}
	}
	
	public interface IFac_elecEntityUnitOfWork : IUnitOfWork
	{
		IQueryable<srv_origen> srv_origens
		{
			get;
		}
		IQueryable<base_firmada> base_firmadas
		{
			get;
		}
		IQueryable<base_loc> base_locs
		{
			get;
		}
	}
}
#pragma warning restore 1591
