#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DatosFacturaLib	
{
	public partial class Cau_FIN_FACEInvoiceHeader
	{
		private decimal _totalAmount;
		public virtual decimal TotalAmount
		{
			get
			{
				return this._totalAmount;
			}
			set
			{
				this._totalAmount = value;
			}
		}
		
		private string _currencyCode;
		public virtual string CurrencyCode
		{
			get
			{
				return this._currencyCode;
			}
			set
			{
				this._currencyCode = value;
			}
		}
		
		private string _sellerTaxIdentificationNumber;
		public virtual string SellerTaxIdentificationNumber
		{
			get
			{
				return this._sellerTaxIdentificationNumber;
			}
			set
			{
				this._sellerTaxIdentificationNumber = value;
			}
		}
		
		private string _sellerCorporateName;
		public virtual string SellerCorporateName
		{
			get
			{
				return this._sellerCorporateName;
			}
			set
			{
				this._sellerCorporateName = value;
			}
		}
		
		private string _sellerAddress;
		public virtual string SellerAddress
		{
			get
			{
				return this._sellerAddress;
			}
			set
			{
				this._sellerAddress = value;
			}
		}
		
		private string _sellerPostCode;
		public virtual string SellerPostCode
		{
			get
			{
				return this._sellerPostCode;
			}
			set
			{
				this._sellerPostCode = value;
			}
		}
		
		private string _sellerCountryCode;
		public virtual string SellerCountryCode
		{
			get
			{
				return this._sellerCountryCode;
			}
			set
			{
				this._sellerCountryCode = value;
			}
		}
		
		private string _sellerProvince;
		public virtual string SellerProvince
		{
			get
			{
				return this._sellerProvince;
			}
			set
			{
				this._sellerProvince = value;
			}
		}
		
		private string _sellerTown;
		public virtual string SellerTown
		{
			get
			{
				return this._sellerTown;
			}
			set
			{
				this._sellerTown = value;
			}
		}
		
		private string _buyerTaxIdentificationNumber;
		public virtual string BuyerTaxIdentificationNumber
		{
			get
			{
				return this._buyerTaxIdentificationNumber;
			}
			set
			{
				this._buyerTaxIdentificationNumber = value;
			}
		}
		
		private string _buyerCorporateName;
		public virtual string BuyerCorporateName
		{
			get
			{
				return this._buyerCorporateName;
			}
			set
			{
				this._buyerCorporateName = value;
			}
		}
		
		private string _buyerAddress;
		public virtual string BuyerAddress
		{
			get
			{
				return this._buyerAddress;
			}
			set
			{
				this._buyerAddress = value;
			}
		}
		
		private string _buyerPostCode;
		public virtual string BuyerPostCode
		{
			get
			{
				return this._buyerPostCode;
			}
			set
			{
				this._buyerPostCode = value;
			}
		}
		
		private string _buyerCountryCode;
		public virtual string BuyerCountryCode
		{
			get
			{
				return this._buyerCountryCode;
			}
			set
			{
				this._buyerCountryCode = value;
			}
		}
		
		private string _invoiceNumber;
		public virtual string InvoiceNumber
		{
			get
			{
				return this._invoiceNumber;
			}
			set
			{
				this._invoiceNumber = value;
			}
		}
		
		private DateTime _issueDate;
		public virtual DateTime IssueDate
		{
			get
			{
				return this._issueDate;
			}
			set
			{
				this._issueDate = value;
			}
		}
		
		private string _invoiceCurrencyCode;
		public virtual string InvoiceCurrencyCode
		{
			get
			{
				return this._invoiceCurrencyCode;
			}
			set
			{
				this._invoiceCurrencyCode = value;
			}
		}
		
		private string _languageName;
		public virtual string LanguageName
		{
			get
			{
				return this._languageName;
			}
			set
			{
				this._languageName = value;
			}
		}
		
		private string _taxCurrencyCode;
		public virtual string TaxCurrencyCode
		{
			get
			{
				return this._taxCurrencyCode;
			}
			set
			{
				this._taxCurrencyCode = value;
			}
		}
		
		private string _dATAAREAID;
		public virtual string DATAAREAID
		{
			get
			{
				return this._dATAAREAID;
			}
			set
			{
				this._dATAAREAID = value;
			}
		}
		
		private string _iD;
		public virtual string ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private decimal _totalGrossAmount;
		public virtual decimal TotalGrossAmount
		{
			get
			{
				return this._totalGrossAmount;
			}
			set
			{
				this._totalGrossAmount = value;
			}
		}
		
		private decimal _totalGrossAmountBeforeTaxes;
		public virtual decimal TotalGrossAmountBeforeTaxes
		{
			get
			{
				return this._totalGrossAmountBeforeTaxes;
			}
			set
			{
				this._totalGrossAmountBeforeTaxes = value;
			}
		}
		
		private decimal _totalTaxOutputs;
		public virtual decimal TotalTaxOutputs
		{
			get
			{
				return this._totalTaxOutputs;
			}
			set
			{
				this._totalTaxOutputs = value;
			}
		}
		
		private decimal _invoiceTotals;
		public virtual decimal InvoiceTotals
		{
			get
			{
				return this._invoiceTotals;
			}
			set
			{
				this._invoiceTotals = value;
			}
		}
		
		private decimal _totalOutstandingAmount;
		public virtual decimal TotalOutstandingAmount
		{
			get
			{
				return this._totalOutstandingAmount;
			}
			set
			{
				this._totalOutstandingAmount = value;
			}
		}
		
		private decimal _totalExecutableAmount;
		public virtual decimal TotalExecutableAmount
		{
			get
			{
				return this._totalExecutableAmount;
			}
			set
			{
				this._totalExecutableAmount = value;
			}
		}
		
		private string _cODIGOUNIDADTRAMITADORA;
		public virtual string CODIGOUNIDADTRAMITADORA
		{
			get
			{
				return this._cODIGOUNIDADTRAMITADORA;
			}
			set
			{
				this._cODIGOUNIDADTRAMITADORA = value;
			}
		}
		
		private string _cODIGOORGANOGESTOR;
		public virtual string CODIGOORGANOGESTOR
		{
			get
			{
				return this._cODIGOORGANOGESTOR;
			}
			set
			{
				this._cODIGOORGANOGESTOR = value;
			}
		}
		
		private string _cODIGOOFICINACONTABLE;
		public virtual string CODIGOOFICINACONTABLE
		{
			get
			{
				return this._cODIGOOFICINACONTABLE;
			}
			set
			{
				this._cODIGOOFICINACONTABLE = value;
			}
		}
		
		private string _buyerProvince;
		public virtual string BuyerProvince
		{
			get
			{
				return this._buyerProvince;
			}
			set
			{
				this._buyerProvince = value;
			}
		}
		
		private string _buyerTown;
		public virtual string BuyerTown
		{
			get
			{
				return this._buyerTown;
			}
			set
			{
				this._buyerTown = value;
			}
		}
		
		private DateTime _installmentDueDate;
		public virtual DateTime InstallmentDueDate
		{
			get
			{
				return this._installmentDueDate;
			}
			set
			{
				this._installmentDueDate = value;
			}
		}
		
		private decimal _installmentAmount;
		public virtual decimal InstallmentAmount
		{
			get
			{
				return this._installmentAmount;
			}
			set
			{
				this._installmentAmount = value;
			}
		}
		
		private string _paymentMeans;
		public virtual string PaymentMeans
		{
			get
			{
				return this._paymentMeans;
			}
			set
			{
				this._paymentMeans = value;
			}
		}
		
		private string _iBAN;
		public virtual string IBAN
		{
			get
			{
				return this._iBAN;
			}
			set
			{
				this._iBAN = value;
			}
		}
		
	}
}
#pragma warning restore 1591
