#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DatosFacturaLib	
{
	public partial class Cau_FIN_FACEInvoiceTax
	{
		private decimal _taxRate;
		public virtual decimal TaxRate
		{
			get
			{
				return this._taxRate;
			}
			set
			{
				this._taxRate = value;
			}
		}
		
		private string _iD;
		public virtual string ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _invoiceNumber;
		public virtual string InvoiceNumber
		{
			get
			{
				return this._invoiceNumber;
			}
			set
			{
				this._invoiceNumber = value;
			}
		}
		
		private decimal? _tAXBASEAMOUNT;
		public virtual decimal? TAXBASEAMOUNT
		{
			get
			{
				return this._tAXBASEAMOUNT;
			}
			set
			{
				this._tAXBASEAMOUNT = value;
			}
		}
		
		private decimal? _tAXAMOUNT;
		public virtual decimal? TAXAMOUNT
		{
			get
			{
				return this._tAXAMOUNT;
			}
			set
			{
				this._tAXAMOUNT = value;
			}
		}
		
	}
}
#pragma warning restore 1591
