#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DatosFacturaLib;

namespace DatosFacturaLib	
{
	public partial class Empresa
	{
		private int idEmpresa;
		public virtual int Id_empresa
		{
			get
			{
				return this.idEmpresa;
			}
			set
			{
				this.idEmpresa = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private string cif;
		public virtual string Cif
		{
			get
			{
				return this.cif;
			}
			set
			{
				this.cif = value;
			}
		}
		
		private string tomo;
		public virtual string Tomo
		{
			get
			{
				return this.tomo;
			}
			set
			{
				this.tomo = value;
			}
		}
		
		private string seccion;
		public virtual string Seccion
		{
			get
			{
				return this.seccion;
			}
			set
			{
				this.seccion = value;
			}
		}
		
		private string registro;
		public virtual string Registro
		{
			get
			{
				return this.registro;
			}
			set
			{
				this.registro = value;
			}
		}
		
		private string regcomentarios;
		public virtual string Regcomentarios
		{
			get
			{
				return this.regcomentarios;
			}
			set
			{
				this.regcomentarios = value;
			}
		}
		
		private string libro;
		public virtual string Libro
		{
			get
			{
				return this.libro;
			}
			set
			{
				this.libro = value;
			}
		}
		
		private string hoja;
		public virtual string Hoja
		{
			get
			{
				return this.hoja;
			}
			set
			{
				this.hoja = value;
			}
		}
		
		private string folio;
		public virtual string Folio
		{
			get
			{
				return this.folio;
			}
			set
			{
				this.folio = value;
			}
		}
		
		private IList<Superusuario> superusuarios = new List<Superusuario>();
		public virtual IList<Superusuario> Superusuarios
		{
			get
			{
				return this.superusuarios;
			}
		}
		
		private IList<Cliente> clientes = new List<Cliente>();
		public virtual IList<Cliente> Clientes
		{
			get
			{
				return this.clientes;
			}
		}
		
	}
}
#pragma warning restore 1591
