#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DatosFacturaLib;

namespace DatosFacturaLib	
{
	public partial class Factura
	{
		private int idFactura;
		public virtual int Id_factura
		{
			get
			{
				return this.idFactura;
			}
			set
			{
				this.idFactura = value;
			}
		}
		
		private DateTime? fecha;
		public virtual DateTime? Fecha
		{
			get
			{
				return this.fecha;
			}
			set
			{
				this.fecha = value;
			}
		}
		
		private decimal? baseTotal;
		public virtual decimal? Base_total
		{
			get
			{
				return this.baseTotal;
			}
			set
			{
				this.baseTotal = value;
			}
		}
		
		private decimal? cuotaTotal;
		public virtual decimal? Cuota_total
		{
			get
			{
				return this.cuotaTotal;
			}
			set
			{
				this.cuotaTotal = value;
			}
		}
		
		private decimal? ttal;
		public virtual decimal? Ttal
		{
			get
			{
				return this.ttal;
			}
			set
			{
				this.ttal = value;
			}
		}
		
		private string numSerie;
		public virtual string Num_serie
		{
			get
			{
				return this.numSerie;
			}
			set
			{
				this.numSerie = value;
			}
		}
		
		private int? numFactura;
		public virtual int? Num_factura
		{
			get
			{
				return this.numFactura;
			}
			set
			{
				this.numFactura = value;
			}
		}
		
		private int? idCliente;
		public virtual int? Id_cliente
		{
			get
			{
				return this.idCliente;
			}
			set
			{
				this.idCliente = value;
			}
		}
		
		private bool? nueva;
		public virtual bool? Nueva
		{
			get
			{
				return this.nueva;
			}
			set
			{
				this.nueva = value;
			}
		}
		
		private int coddirecAriges;
		public virtual int coddirec_ariges
		{
			get
			{
				return this.coddirecAriges;
			}
			set
			{
				this.coddirecAriges = value;
			}
		}
		
		private string unidadTramitadoraCodigo;
		public virtual string UnidadTramitadoraCodigo
		{
			get
			{
				return this.unidadTramitadoraCodigo;
			}
			set
			{
				this.unidadTramitadoraCodigo = value;
			}
		}
		
		private string organoGestorCodigo;
		public virtual string OrganoGestorCodigo
		{
			get
			{
				return this.organoGestorCodigo;
			}
			set
			{
				this.organoGestorCodigo = value;
			}
		}
		
		private string oficinaContableCodigo;
		public virtual string OficinaContableCodigo
		{
			get
			{
				return this.oficinaContableCodigo;
			}
			set
			{
				this.oficinaContableCodigo = value;
			}
		}
		
		private string codDirecGdes;
		public virtual string CodDirecGdes
		{
			get
			{
				return this.codDirecGdes;
			}
			set
			{
				this.codDirecGdes = value;
			}
		}
		
		private string sistemaGdes;
		public virtual string SistemaGdes
		{
			get
			{
				return this.sistemaGdes;
			}
			set
			{
				this.sistemaGdes = value;
			}
		}
		
		private bool esFraCliente;
		public virtual bool EsFraCliente
		{
			get
			{
				return this.esFraCliente;
			}
			set
			{
				this.esFraCliente = value;
			}
		}
		
		private decimal impRetencion;
		public virtual decimal ImpRetencion
		{
			get
			{
				return this.impRetencion;
			}
			set
			{
				this.impRetencion = value;
			}
		}
		
		private string letraIdFraProve;
		public virtual string LetraIdFraProve
		{
			get
			{
				return this.letraIdFraProve;
			}
			set
			{
				this.letraIdFraProve = value;
			}
		}
		
		private int sistema_id;
		public virtual int Sistema_id
		{
			get
			{
				return this.sistema_id;
			}
			set
			{
				this.sistema_id = value;
			}
		}
		
		private decimal impGastosAFo;
		public virtual decimal ImpGastosAFo
		{
			get
			{
				return this.impGastosAFo;
			}
			set
			{
				this.impGastosAFo = value;
			}
		}
		
		private string vCodtipom1;
		public virtual string vCodtipom
		{
			get
			{
				return this.vCodtipom1;
			}
			set
			{
				this.vCodtipom1 = value;
			}
		}
		
		private Cliente cliente;
		public virtual Cliente Cliente
		{
			get
			{
				return this.cliente;
			}
			set
			{
				this.cliente = value;
			}
		}
		
		private Sistema sistema;
		public virtual Sistema Sistema
		{
			get
			{
				return this.sistema;
			}
			set
			{
				this.sistema = value;
			}
		}
		
	}
}
#pragma warning restore 1591
