#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DatosFacturaLib	
{
	public partial class Firma
	{
		private int idFirma;
		public virtual int Id_firma
		{
			get
			{
				return this.idFirma;
			}
			set
			{
				this.idFirma = value;
			}
		}
		
		private string tsaUrl;
		public virtual string Tsa_url
		{
			get
			{
				return this.tsaUrl;
			}
			set
			{
				this.tsaUrl = value;
			}
		}
		
		private string tsaUser;
		public virtual string Tsa_user
		{
			get
			{
				return this.tsaUser;
			}
			set
			{
				this.tsaUser = value;
			}
		}
		
		private string tsaPass;
		public virtual string Tsa_pass
		{
			get
			{
				return this.tsaPass;
			}
			set
			{
				this.tsaPass = value;
			}
		}
		
		private string certificadoPath;
		public virtual string Certificado_path
		{
			get
			{
				return this.certificadoPath;
			}
			set
			{
				this.certificadoPath = value;
			}
		}
		
		private string certificadoPass;
		public virtual string Certificado_pass
		{
			get
			{
				return this.certificadoPass;
			}
			set
			{
				this.certificadoPass = value;
			}
		}
		
		private string motivo;
		public virtual string Motivo
		{
			get
			{
				return this.motivo;
			}
			set
			{
				this.motivo = value;
			}
		}
		
		private string lugar;
		public virtual string Lugar
		{
			get
			{
				return this.lugar;
			}
			set
			{
				this.lugar = value;
			}
		}
		
		private string logoPath;
		public virtual string Logo_path
		{
			get
			{
				return this.logoPath;
			}
			set
			{
				this.logoPath = value;
			}
		}
		
		private int? posicionX0;
		public virtual int? Posicion_x0
		{
			get
			{
				return this.posicionX0;
			}
			set
			{
				this.posicionX0 = value;
			}
		}
		
		private int? posicionY0;
		public virtual int? Posicion_y0
		{
			get
			{
				return this.posicionY0;
			}
			set
			{
				this.posicionY0 = value;
			}
		}
		
		private int? posicionXX;
		public virtual int? Posicion_x_x
		{
			get
			{
				return this.posicionXX;
			}
			set
			{
				this.posicionXX = value;
			}
		}
		
		private int? posicionYY;
		public virtual int? Posicion_y_y
		{
			get
			{
				return this.posicionYY;
			}
			set
			{
				this.posicionYY = value;
			}
		}
		
	}
}
#pragma warning restore 1591
