#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DatosFacturaLib	
{
	public partial class Plantilla
	{
		private string contenido;
		public virtual string Contenido
		{
			get
			{
				return this.contenido;
			}
			set
			{
				this.contenido = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private int plantilla_id;
		public virtual int Plantilla_id
		{
			get
			{
				return this.plantilla_id;
			}
			set
			{
				this.plantilla_id = value;
			}
		}
		
	}
}
#pragma warning restore 1591
