#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DatosFacturaLib	
{
	public partial class Unidad
	{
		private string organoGestorCodigo;
		public virtual string OrganoGestorCodigo
		{
			get
			{
				return this.organoGestorCodigo;
			}
			set
			{
				this.organoGestorCodigo = value;
			}
		}
		
		private string unidadTramitadoraCodigo;
		public virtual string UnidadTramitadoraCodigo
		{
			get
			{
				return this.unidadTramitadoraCodigo;
			}
			set
			{
				this.unidadTramitadoraCodigo = value;
			}
		}
		
		private string oficinaContableCodigo;
		public virtual string OficinaContableCodigo
		{
			get
			{
				return this.oficinaContableCodigo;
			}
			set
			{
				this.oficinaContableCodigo = value;
			}
		}
		
		private string organoGestorNombre;
		public virtual string OrganoGestorNombre
		{
			get
			{
				return this.organoGestorNombre;
			}
			set
			{
				this.organoGestorNombre = value;
			}
		}
		
		private string unidadTramitadoraNombre;
		public virtual string UnidadTramitadoraNombre
		{
			get
			{
				return this.unidadTramitadoraNombre;
			}
			set
			{
				this.unidadTramitadoraNombre = value;
			}
		}
		
		private string oficinaContableNombre;
		public virtual string OficinaContableNombre
		{
			get
			{
				return this.oficinaContableNombre;
			}
			set
			{
				this.oficinaContableNombre = value;
			}
		}
		
	}
}
#pragma warning restore 1591
