#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace DatosFacturaLib	
{
	public partial class Usuario
	{
		private int usuarioId;
		public virtual int UsuarioId
		{
			get
			{
				return this.usuarioId;
			}
			set
			{
				this.usuarioId = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private string login;
		public virtual string Login
		{
			get
			{
				return this.login;
			}
			set
			{
				this.login = value;
			}
		}
		
		private string password;
		public virtual string Password
		{
			get
			{
				return this.password;
			}
			set
			{
				this.password = value;
			}
		}
		
		private string email;
		public virtual string Email
		{
			get
			{
				return this.email;
			}
			set
			{
				this.email = value;
			}
		}
		
		private string nif;
		public virtual string Nif
		{
			get
			{
				return this.nif;
			}
			set
			{
				this.nif = value;
			}
		}
		
		private int? clienteId;
		public virtual int? ClienteId
		{
			get
			{
				return this.clienteId;
			}
			set
			{
				this.clienteId = value;
			}
		}
		
		private int? departamentoId;
		public virtual int? DepartamentoId
		{
			get
			{
				return this.departamentoId;
			}
			set
			{
				this.departamentoId = value;
			}
		}
		
	}
}
#pragma warning restore 1591
