#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace AriTaxiModel	
{
	public partial class Sartic
	{
		private string _codartic;
		public virtual string Codartic
		{
			get
			{
				return this._codartic;
			}
			set
			{
				this._codartic = value;
			}
		}
		
		private string _nomartic;
		public virtual string Nomartic
		{
			get
			{
				return this._nomartic;
			}
			set
			{
				this._nomartic = value;
			}
		}
		
		private string _codtelem;
		public virtual string Codtelem
		{
			get
			{
				return this._codtelem;
			}
			set
			{
				this._codtelem = value;
			}
		}
		
		private uint _codprove;
		public virtual uint Codprove
		{
			get
			{
				return this._codprove;
			}
			set
			{
				this._codprove = value;
			}
		}
		
		private ushort _codfamia;
		public virtual ushort Codfamia
		{
			get
			{
				return this._codfamia;
			}
			set
			{
				this._codfamia = value;
			}
		}
		
		private ushort _codmarca;
		public virtual ushort Codmarca
		{
			get
			{
				return this._codmarca;
			}
			set
			{
				this._codmarca = value;
			}
		}
		
		private ushort _codunida;
		public virtual ushort Codunida
		{
			get
			{
				return this._codunida;
			}
			set
			{
				this._codunida = value;
			}
		}
		
		private string _codtipar;
		public virtual string Codtipar
		{
			get
			{
				return this._codtipar;
			}
			set
			{
				this._codtipar = value;
			}
		}
		
		private ushort _codstatu;
		public virtual ushort Codstatu
		{
			get
			{
				return this._codstatu;
			}
			set
			{
				this._codstatu = value;
			}
		}
		
		private byte _codigiva;
		public virtual byte Codigiva
		{
			get
			{
				return this._codigiva;
			}
			set
			{
				this._codigiva = value;
			}
		}
		
		private ushort _artvario;
		public virtual ushort Artvario
		{
			get
			{
				return this._artvario;
			}
			set
			{
				this._artvario = value;
			}
		}
		
		private byte _conjunto;
		public virtual byte Conjunto
		{
			get
			{
				return this._conjunto;
			}
			set
			{
				this._conjunto = value;
			}
		}
		
		private byte _nseriesn;
		public virtual byte Nseriesn
		{
			get
			{
				return this._nseriesn;
			}
			set
			{
				this._nseriesn = value;
			}
		}
		
		private ushort _garantia;
		public virtual ushort Garantia
		{
			get
			{
				return this._garantia;
			}
			set
			{
				this._garantia = value;
			}
		}
		
		private decimal? _preciomp;
		public virtual decimal? Preciomp
		{
			get
			{
				return this._preciomp;
			}
			set
			{
				this._preciomp = value;
			}
		}
		
		private decimal? _precioma;
		public virtual decimal? Precioma
		{
			get
			{
				return this._precioma;
			}
			set
			{
				this._precioma = value;
			}
		}
		
		private decimal? _preciouc;
		public virtual decimal? Preciouc
		{
			get
			{
				return this._preciouc;
			}
			set
			{
				this._preciouc = value;
			}
		}
		
		private decimal? _preciost;
		public virtual decimal? Preciost
		{
			get
			{
				return this._preciost;
			}
			set
			{
				this._preciost = value;
			}
		}
		
		private decimal _preciove;
		public virtual decimal Preciove
		{
			get
			{
				return this._preciove;
			}
			set
			{
				this._preciove = value;
			}
		}
		
		private DateTime? _ultfecco;
		public virtual DateTime? Ultfecco
		{
			get
			{
				return this._ultfecco;
			}
			set
			{
				this._ultfecco = value;
			}
		}
		
		private DateTime? _ultfecpvp;
		public virtual DateTime? Ultfecpvp
		{
			get
			{
				return this._ultfecpvp;
			}
			set
			{
				this._ultfecpvp = value;
			}
		}
		
		private ushort _unicajas;
		public virtual ushort Unicajas
		{
			get
			{
				return this._unicajas;
			}
			set
			{
				this._unicajas = value;
			}
		}
		
		private DateTime _fecaltas;
		public virtual DateTime Fecaltas
		{
			get
			{
				return this._fecaltas;
			}
			set
			{
				this._fecaltas = value;
			}
		}
		
		private string _textoven;
		public virtual string Textoven
		{
			get
			{
				return this._textoven;
			}
			set
			{
				this._textoven = value;
			}
		}
		
		private string _textocom;
		public virtual string Textocom
		{
			get
			{
				return this._textocom;
			}
			set
			{
				this._textocom = value;
			}
		}
		
		private string _controli;
		public virtual string Controli
		{
			get
			{
				return this._controli;
			}
			set
			{
				this._controli = value;
			}
		}
		
		private byte _ctrstock;
		public virtual byte Ctrstock
		{
			get
			{
				return this._ctrstock;
			}
			set
			{
				this._ctrstock = value;
			}
		}
		
		private decimal? _margecom;
		public virtual decimal? Margecom
		{
			get
			{
				return this._margecom;
			}
			set
			{
				this._margecom = value;
			}
		}
		
		private decimal? _preanuman;
		public virtual decimal? Preanuman
		{
			get
			{
				return this._preanuman;
			}
			set
			{
				this._preanuman = value;
			}
		}
		
		private string _txtauxdocumento;
		public virtual string Txtauxdocumento
		{
			get
			{
				return this._txtauxdocumento;
			}
			set
			{
				this._txtauxdocumento = value;
			}
		}
		
		private decimal? _pesoarti;
		public virtual decimal? Pesoarti
		{
			get
			{
				return this._pesoarti;
			}
			set
			{
				this._pesoarti = value;
			}
		}
		
		private short _mateprima;
		public virtual short Mateprima
		{
			get
			{
				return this._mateprima;
			}
			set
			{
				this._mateprima = value;
			}
		}
		
		private int _numorden;
		public virtual int Numorden
		{
			get
			{
				return this._numorden;
			}
			set
			{
				this._numorden = value;
			}
		}
		
	}
}
#pragma warning restore 1591
