#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriTaxiModel;

namespace AriTaxiModel	
{
	public partial class Sbanpr
	{
		private short _codbanpr;
		public virtual short Codbanpr
		{
			get
			{
				return this._codbanpr;
			}
			set
			{
				this._codbanpr = value;
			}
		}
		
		private string _iban;
		public virtual string Iban
		{
			get
			{
				return this._iban;
			}
			set
			{
				this._iban = value;
			}
		}
		
		private ushort _codbanco;
		public virtual ushort Codbanco
		{
			get
			{
				return this._codbanco;
			}
			set
			{
				this._codbanco = value;
			}
		}
		
		private ushort _codsucur;
		public virtual ushort Codsucur
		{
			get
			{
				return this._codsucur;
			}
			set
			{
				this._codsucur = value;
			}
		}
		
		private string _digcontr;
		public virtual string Digcontr
		{
			get
			{
				return this._digcontr;
			}
			set
			{
				this._digcontr = value;
			}
		}
		
		private string _cuentaba;
		public virtual string Cuentaba
		{
			get
			{
				return this._cuentaba;
			}
			set
			{
				this._cuentaba = value;
			}
		}
		
		private IList<Scliente> _sclientes = new List<Scliente>();
		public virtual IList<Scliente> Sclientes
		{
			get
			{
				return this._sclientes;
			}
		}
		
	}
}
#pragma warning restore 1591
