#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriTaxiModel;

namespace AriTaxiModel	
{
	public partial class Scafaccli
	{
		private string _codtipom;
		public virtual string Codtipom
		{
			get
			{
				return this._codtipom;
			}
			set
			{
				this._codtipom = value;
			}
		}
		
		private uint _numfactu;
		public virtual uint Numfactu
		{
			get
			{
				return this._numfactu;
			}
			set
			{
				this._numfactu = value;
			}
		}
		
		private DateTime _fecfactu;
		public virtual DateTime Fecfactu
		{
			get
			{
				return this._fecfactu;
			}
			set
			{
				this._fecfactu = value;
			}
		}
		
		private uint _codclien;
		public virtual uint Codclien
		{
			get
			{
				return this._codclien;
			}
			set
			{
				this._codclien = value;
			}
		}
		
		private string _nomclien;
		public virtual string Nomclien
		{
			get
			{
				return this._nomclien;
			}
			set
			{
				this._nomclien = value;
			}
		}
		
		private string _domclien;
		public virtual string Domclien
		{
			get
			{
				return this._domclien;
			}
			set
			{
				this._domclien = value;
			}
		}
		
		private string _codpobla;
		public virtual string Codpobla
		{
			get
			{
				return this._codpobla;
			}
			set
			{
				this._codpobla = value;
			}
		}
		
		private string _pobclien;
		public virtual string Pobclien
		{
			get
			{
				return this._pobclien;
			}
			set
			{
				this._pobclien = value;
			}
		}
		
		private string _proclien;
		public virtual string Proclien
		{
			get
			{
				return this._proclien;
			}
			set
			{
				this._proclien = value;
			}
		}
		
		private string _nifclien;
		public virtual string Nifclien
		{
			get
			{
				return this._nifclien;
			}
			set
			{
				this._nifclien = value;
			}
		}
		
		private string _telclien;
		public virtual string Telclien
		{
			get
			{
				return this._telclien;
			}
			set
			{
				this._telclien = value;
			}
		}
		
		private ushort? _coddirec;
		public virtual ushort? Coddirec
		{
			get
			{
				return this._coddirec;
			}
			set
			{
				this._coddirec = value;
			}
		}
		
		private string _nomdirec;
		public virtual string Nomdirec
		{
			get
			{
				return this._nomdirec;
			}
			set
			{
				this._nomdirec = value;
			}
		}
		
		private ushort _codagent;
		public virtual ushort Codagent
		{
			get
			{
				return this._codagent;
			}
			set
			{
				this._codagent = value;
			}
		}
		
		private ushort _codforpa;
		public virtual ushort Codforpa
		{
			get
			{
				return this._codforpa;
			}
			set
			{
				this._codforpa = value;
			}
		}
		
		private decimal _dtoppago;
		public virtual decimal Dtoppago
		{
			get
			{
				return this._dtoppago;
			}
			set
			{
				this._dtoppago = value;
			}
		}
		
		private decimal _dtognral;
		public virtual decimal Dtognral
		{
			get
			{
				return this._dtognral;
			}
			set
			{
				this._dtognral = value;
			}
		}
		
		private ushort? _codbanco;
		public virtual ushort? Codbanco
		{
			get
			{
				return this._codbanco;
			}
			set
			{
				this._codbanco = value;
			}
		}
		
		private ushort? _codsucur;
		public virtual ushort? Codsucur
		{
			get
			{
				return this._codsucur;
			}
			set
			{
				this._codsucur = value;
			}
		}
		
		private string _digcontr;
		public virtual string Digcontr
		{
			get
			{
				return this._digcontr;
			}
			set
			{
				this._digcontr = value;
			}
		}
		
		private string _cuentaba;
		public virtual string Cuentaba
		{
			get
			{
				return this._cuentaba;
			}
			set
			{
				this._cuentaba = value;
			}
		}
		
		private decimal _brutofac;
		public virtual decimal Brutofac
		{
			get
			{
				return this._brutofac;
			}
			set
			{
				this._brutofac = value;
			}
		}
		
		private decimal _impdtopp;
		public virtual decimal Impdtopp
		{
			get
			{
				return this._impdtopp;
			}
			set
			{
				this._impdtopp = value;
			}
		}
		
		private decimal _impdtogr;
		public virtual decimal Impdtogr
		{
			get
			{
				return this._impdtogr;
			}
			set
			{
				this._impdtogr = value;
			}
		}
		
		private decimal _baseimp1;
		public virtual decimal Baseimp1
		{
			get
			{
				return this._baseimp1;
			}
			set
			{
				this._baseimp1 = value;
			}
		}
		
		private decimal? _baseimp2;
		public virtual decimal? Baseimp2
		{
			get
			{
				return this._baseimp2;
			}
			set
			{
				this._baseimp2 = value;
			}
		}
		
		private decimal? _baseimp3;
		public virtual decimal? Baseimp3
		{
			get
			{
				return this._baseimp3;
			}
			set
			{
				this._baseimp3 = value;
			}
		}
		
		private byte? _codigiv1;
		public virtual byte? Codigiv1
		{
			get
			{
				return this._codigiv1;
			}
			set
			{
				this._codigiv1 = value;
			}
		}
		
		private byte? _codigiv2;
		public virtual byte? Codigiv2
		{
			get
			{
				return this._codigiv2;
			}
			set
			{
				this._codigiv2 = value;
			}
		}
		
		private byte? _codigiv3;
		public virtual byte? Codigiv3
		{
			get
			{
				return this._codigiv3;
			}
			set
			{
				this._codigiv3 = value;
			}
		}
		
		private decimal? _porciva1;
		public virtual decimal? Porciva1
		{
			get
			{
				return this._porciva1;
			}
			set
			{
				this._porciva1 = value;
			}
		}
		
		private decimal? _porciva2;
		public virtual decimal? Porciva2
		{
			get
			{
				return this._porciva2;
			}
			set
			{
				this._porciva2 = value;
			}
		}
		
		private decimal? _porciva3;
		public virtual decimal? Porciva3
		{
			get
			{
				return this._porciva3;
			}
			set
			{
				this._porciva3 = value;
			}
		}
		
		private decimal _imporiv1;
		public virtual decimal Imporiv1
		{
			get
			{
				return this._imporiv1;
			}
			set
			{
				this._imporiv1 = value;
			}
		}
		
		private decimal? _imporiv2;
		public virtual decimal? Imporiv2
		{
			get
			{
				return this._imporiv2;
			}
			set
			{
				this._imporiv2 = value;
			}
		}
		
		private decimal? _imporiv3;
		public virtual decimal? Imporiv3
		{
			get
			{
				return this._imporiv3;
			}
			set
			{
				this._imporiv3 = value;
			}
		}
		
		private decimal _totalfac;
		public virtual decimal Totalfac
		{
			get
			{
				return this._totalfac;
			}
			set
			{
				this._totalfac = value;
			}
		}
		
		private byte? _intconta;
		public virtual byte? Intconta
		{
			get
			{
				return this._intconta;
			}
			set
			{
				this._intconta = value;
			}
		}
		
		private decimal? _porciva1re;
		public virtual decimal? Porciva1re
		{
			get
			{
				return this._porciva1re;
			}
			set
			{
				this._porciva1re = value;
			}
		}
		
		private decimal? _porciva2re;
		public virtual decimal? Porciva2re
		{
			get
			{
				return this._porciva2re;
			}
			set
			{
				this._porciva2re = value;
			}
		}
		
		private decimal? _porciva3re;
		public virtual decimal? Porciva3re
		{
			get
			{
				return this._porciva3re;
			}
			set
			{
				this._porciva3re = value;
			}
		}
		
		private decimal? _imporiv1re;
		public virtual decimal? Imporiv1re
		{
			get
			{
				return this._imporiv1re;
			}
			set
			{
				this._imporiv1re = value;
			}
		}
		
		private decimal? _imporiv2re;
		public virtual decimal? Imporiv2re
		{
			get
			{
				return this._imporiv2re;
			}
			set
			{
				this._imporiv2re = value;
			}
		}
		
		private decimal? _imporiv3re;
		public virtual decimal? Imporiv3re
		{
			get
			{
				return this._imporiv3re;
			}
			set
			{
				this._imporiv3re = value;
			}
		}
		
		private int? _aridoc;
		public virtual int? Aridoc
		{
			get
			{
				return this._aridoc;
			}
			set
			{
				this._aridoc = value;
			}
		}
		
		private decimal? _aportacion;
		public virtual decimal? Aportacion
		{
			get
			{
				return this._aportacion;
			}
			set
			{
				this._aportacion = value;
			}
		}
		
		private decimal? _pesoalba;
		public virtual decimal? Pesoalba
		{
			get
			{
				return this._pesoalba;
			}
			set
			{
				this._pesoalba = value;
			}
		}
		
		private decimal? _portes;
		public virtual decimal? Portes
		{
			get
			{
				return this._portes;
			}
			set
			{
				this._portes = value;
			}
		}
		
		private int? _numservi;
		public virtual int? Numservi
		{
			get
			{
				return this._numservi;
			}
			set
			{
				this._numservi = value;
			}
		}
		
		private decimal? _suplidos;
		public virtual decimal? Suplidos
		{
			get
			{
				return this._suplidos;
			}
			set
			{
				this._suplidos = value;
			}
		}
		
		private byte _exportada;
		public virtual byte Exportada
		{
			get
			{
				return this._exportada;
			}
			set
			{
				this._exportada = value;
			}
		}
		
		private DateTime _fecdesde;
		public virtual DateTime Fecdesde
		{
			get
			{
				return this._fecdesde;
			}
			set
			{
				this._fecdesde = value;
			}
		}
		
		private DateTime _fechasta;
		public virtual DateTime Fechasta
		{
			get
			{
				return this._fechasta;
			}
			set
			{
				this._fechasta = value;
			}
		}
		
		private Scliente _scliente;
		public virtual Scliente Scliente
		{
			get
			{
				return this._scliente;
			}
			set
			{
				this._scliente = value;
			}
		}
		
		private Svencicli _svencicli;
		public virtual Svencicli Svencicli
		{
			get
			{
				return this._svencicli;
			}
			set
			{
				this._svencicli = value;
			}
		}
		
	}
}
#pragma warning restore 1591
