#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriTaxiModel;

namespace AriTaxiModel	
{
	public partial class Sclien
	{
		private uint _codclien;
		public virtual uint Codclien
		{
			get
			{
				return this._codclien;
			}
			set
			{
				this._codclien = value;
			}
		}
		
		private int? _numeruve;
		public virtual int? Numeruve
		{
			get
			{
				return this._numeruve;
			}
			set
			{
				this._numeruve = value;
			}
		}
		
		private string _nomclien;
		public virtual string Nomclien
		{
			get
			{
				return this._nomclien;
			}
			set
			{
				this._nomclien = value;
			}
		}
		
		private string _domclien;
		public virtual string Domclien
		{
			get
			{
				return this._domclien;
			}
			set
			{
				this._domclien = value;
			}
		}
		
		private string _codpobla;
		public virtual string Codpobla
		{
			get
			{
				return this._codpobla;
			}
			set
			{
				this._codpobla = value;
			}
		}
		
		private string _pobclien;
		public virtual string Pobclien
		{
			get
			{
				return this._pobclien;
			}
			set
			{
				this._pobclien = value;
			}
		}
		
		private string _proclien;
		public virtual string Proclien
		{
			get
			{
				return this._proclien;
			}
			set
			{
				this._proclien = value;
			}
		}
		
		private string _nifclien;
		public virtual string Nifclien
		{
			get
			{
				return this._nifclien;
			}
			set
			{
				this._nifclien = value;
			}
		}
		
		private DateTime? _fechabaj;
		public virtual DateTime? Fechabaj
		{
			get
			{
				return this._fechabaj;
			}
			set
			{
				this._fechabaj = value;
			}
		}
		
		private DateTime _fechaalt;
		public virtual DateTime Fechaalt
		{
			get
			{
				return this._fechaalt;
			}
			set
			{
				this._fechaalt = value;
			}
		}
		
		private int? _codcoche;
		public virtual int? Codcoche
		{
			get
			{
				return this._codcoche;
			}
			set
			{
				this._codcoche = value;
			}
		}
		
		private ushort? _codbanco;
		public virtual ushort? Codbanco
		{
			get
			{
				return this._codbanco;
			}
			set
			{
				this._codbanco = value;
			}
		}
		
		private ushort? _codsucur;
		public virtual ushort? Codsucur
		{
			get
			{
				return this._codsucur;
			}
			set
			{
				this._codsucur = value;
			}
		}
		
		private string _digcontr;
		public virtual string Digcontr
		{
			get
			{
				return this._digcontr;
			}
			set
			{
				this._digcontr = value;
			}
		}
		
		private string _cuentaba;
		public virtual string Cuentaba
		{
			get
			{
				return this._cuentaba;
			}
			set
			{
				this._cuentaba = value;
			}
		}
		
		private string _telclie1;
		public virtual string Telclie1
		{
			get
			{
				return this._telclie1;
			}
			set
			{
				this._telclie1 = value;
			}
		}
		
		private string _movclien;
		public virtual string Movclien
		{
			get
			{
				return this._movclien;
			}
			set
			{
				this._movclien = value;
			}
		}
		
		private string _matricul;
		public virtual string Matricul
		{
			get
			{
				return this._matricul;
			}
			set
			{
				this._matricul = value;
			}
		}
		
		private int? _licencia;
		public virtual int? Licencia
		{
			get
			{
				return this._licencia;
			}
			set
			{
				this._licencia = value;
			}
		}
		
		private string _maiclie1;
		public virtual string Maiclie1
		{
			get
			{
				return this._maiclie1;
			}
			set
			{
				this._maiclie1 = value;
			}
		}
		
		private ushort _codsitua;
		public virtual ushort Codsitua
		{
			get
			{
				return this._codsitua;
			}
			set
			{
				this._codsitua = value;
			}
		}
		
		private DateTime? _fechasit;
		public virtual DateTime? Fechasit
		{
			get
			{
				return this._fechasit;
			}
			set
			{
				this._fechasit = value;
			}
		}
		
		private string _observac;
		public virtual string Observac
		{
			get
			{
				return this._observac;
			}
			set
			{
				this._observac = value;
			}
		}
		
		private ushort _codtarif;
		public virtual ushort Codtarif
		{
			get
			{
				return this._codtarif;
			}
			set
			{
				this._codtarif = value;
			}
		}
		
		private string _numpoliza;
		public virtual string Numpoliza
		{
			get
			{
				return this._numpoliza;
			}
			set
			{
				this._numpoliza = value;
			}
		}
		
		private byte _essocio;
		public virtual byte Essocio
		{
			get
			{
				return this._essocio;
			}
			set
			{
				this._essocio = value;
			}
		}
		
		private decimal? _suplecuota;
		public virtual decimal? Suplecuota
		{
			get
			{
				return this._suplecuota;
			}
			set
			{
				this._suplecuota = value;
			}
		}
		
		private decimal? _impacuenta;
		public virtual decimal? Impacuenta
		{
			get
			{
				return this._impacuenta;
			}
			set
			{
				this._impacuenta = value;
			}
		}
		
		private byte _escontado;
		public virtual byte Escontado
		{
			get
			{
				return this._escontado;
			}
			set
			{
				this._escontado = value;
			}
		}
		
		private IList<Sfactusoc> _sfactusocs = new List<Sfactusoc>();
		public virtual IList<Sfactusoc> Sfactusocs
		{
			get
			{
				return this._sfactusocs;
			}
		}
		
		private IList<Scafacuota> _scafacs = new List<Scafacuota>();
		public virtual IList<Scafacuota> Scafacs
		{
			get
			{
				return this._scafacs;
			}
		}
		
	}
}
#pragma warning restore 1591
