#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriTaxiModel;

namespace AriTaxiModel	
{
	public partial class Scliente
	{
		private uint _codclien;
		public virtual uint Codclien
		{
			get
			{
				return this._codclien;
			}
			set
			{
				this._codclien = value;
			}
		}
		
		private string _nomclien;
		public virtual string Nomclien
		{
			get
			{
				return this._nomclien;
			}
			set
			{
				this._nomclien = value;
			}
		}
		
		private string _nomcomer;
		public virtual string Nomcomer
		{
			get
			{
				return this._nomcomer;
			}
			set
			{
				this._nomcomer = value;
			}
		}
		
		private string _domclien;
		public virtual string Domclien
		{
			get
			{
				return this._domclien;
			}
			set
			{
				this._domclien = value;
			}
		}
		
		private string _codpobla;
		public virtual string Codpobla
		{
			get
			{
				return this._codpobla;
			}
			set
			{
				this._codpobla = value;
			}
		}
		
		private string _pobclien;
		public virtual string Pobclien
		{
			get
			{
				return this._pobclien;
			}
			set
			{
				this._pobclien = value;
			}
		}
		
		private string _proclien;
		public virtual string Proclien
		{
			get
			{
				return this._proclien;
			}
			set
			{
				this._proclien = value;
			}
		}
		
		private string _nifclien;
		public virtual string Nifclien
		{
			get
			{
				return this._nifclien;
			}
			set
			{
				this._nifclien = value;
			}
		}
		
		private string _wwwclien;
		public virtual string Wwwclien
		{
			get
			{
				return this._wwwclien;
			}
			set
			{
				this._wwwclien = value;
			}
		}
		
		private DateTime? _fechamov;
		public virtual DateTime? Fechamov
		{
			get
			{
				return this._fechamov;
			}
			set
			{
				this._fechamov = value;
			}
		}
		
		private DateTime _fechaalt;
		public virtual DateTime Fechaalt
		{
			get
			{
				return this._fechaalt;
			}
			set
			{
				this._fechaalt = value;
			}
		}
		
		private ushort _codactiv;
		public virtual ushort Codactiv
		{
			get
			{
				return this._codactiv;
			}
			set
			{
				this._codactiv = value;
			}
		}
		
		private ushort? _codenvio;
		public virtual ushort? Codenvio
		{
			get
			{
				return this._codenvio;
			}
			set
			{
				this._codenvio = value;
			}
		}
		
		private ushort _codagent;
		public virtual ushort Codagent
		{
			get
			{
				return this._codagent;
			}
			set
			{
				this._codagent = value;
			}
		}
		
		private ushort _codforpa;
		public virtual ushort Codforpa
		{
			get
			{
				return this._codforpa;
			}
			set
			{
				this._codforpa = value;
			}
		}
		
		private byte? _diapago1;
		public virtual byte? Diapago1
		{
			get
			{
				return this._diapago1;
			}
			set
			{
				this._diapago1 = value;
			}
		}
		
		private byte? _diapago2;
		public virtual byte? Diapago2
		{
			get
			{
				return this._diapago2;
			}
			set
			{
				this._diapago2 = value;
			}
		}
		
		private byte? _diapago3;
		public virtual byte? Diapago3
		{
			get
			{
				return this._diapago3;
			}
			set
			{
				this._diapago3 = value;
			}
		}
		
		private ushort? _codbanco;
		public virtual ushort? Codbanco
		{
			get
			{
				return this._codbanco;
			}
			set
			{
				this._codbanco = value;
			}
		}
		
		private ushort? _codsucur;
		public virtual ushort? Codsucur
		{
			get
			{
				return this._codsucur;
			}
			set
			{
				this._codsucur = value;
			}
		}
		
		private string _digcontr;
		public virtual string Digcontr
		{
			get
			{
				return this._digcontr;
			}
			set
			{
				this._digcontr = value;
			}
		}
		
		private string _cuentaba;
		public virtual string Cuentaba
		{
			get
			{
				return this._cuentaba;
			}
			set
			{
				this._cuentaba = value;
			}
		}
		
		private string _codmacta;
		public virtual string Codmacta
		{
			get
			{
				return this._codmacta;
			}
			set
			{
				this._codmacta = value;
			}
		}
		
		private string _perclie1;
		public virtual string Perclie1
		{
			get
			{
				return this._perclie1;
			}
			set
			{
				this._perclie1 = value;
			}
		}
		
		private string _telclie1;
		public virtual string Telclie1
		{
			get
			{
				return this._telclie1;
			}
			set
			{
				this._telclie1 = value;
			}
		}
		
		private string _faxclie1;
		public virtual string Faxclie1
		{
			get
			{
				return this._faxclie1;
			}
			set
			{
				this._faxclie1 = value;
			}
		}
		
		private string _maiclie1;
		public virtual string Maiclie1
		{
			get
			{
				return this._maiclie1;
			}
			set
			{
				this._maiclie1 = value;
			}
		}
		
		private string _perclie2;
		public virtual string Perclie2
		{
			get
			{
				return this._perclie2;
			}
			set
			{
				this._perclie2 = value;
			}
		}
		
		private string _telclie2;
		public virtual string Telclie2
		{
			get
			{
				return this._telclie2;
			}
			set
			{
				this._telclie2 = value;
			}
		}
		
		private string _faxclie2;
		public virtual string Faxclie2
		{
			get
			{
				return this._faxclie2;
			}
			set
			{
				this._faxclie2 = value;
			}
		}
		
		private string _maiclie2;
		public virtual string Maiclie2
		{
			get
			{
				return this._maiclie2;
			}
			set
			{
				this._maiclie2 = value;
			}
		}
		
		private byte _clivario;
		public virtual byte Clivario
		{
			get
			{
				return this._clivario;
			}
			set
			{
				this._clivario = value;
			}
		}
		
		private byte _tipoiva;
		public virtual byte Tipoiva
		{
			get
			{
				return this._tipoiva;
			}
			set
			{
				this._tipoiva = value;
			}
		}
		
		private byte _tipofact;
		public virtual byte Tipofact
		{
			get
			{
				return this._tipofact;
			}
			set
			{
				this._tipofact = value;
			}
		}
		
		private byte _albarcon;
		public virtual byte Albarcon
		{
			get
			{
				return this._albarcon;
			}
			set
			{
				this._albarcon = value;
			}
		}
		
		private short _periodof;
		public virtual short Periodof
		{
			get
			{
				return this._periodof;
			}
			set
			{
				this._periodof = value;
			}
		}
		
		private byte? _numrepet;
		public virtual byte? Numrepet
		{
			get
			{
				return this._numrepet;
			}
			set
			{
				this._numrepet = value;
			}
		}
		
		private byte? _mesnogir;
		public virtual byte? Mesnogir
		{
			get
			{
				return this._mesnogir;
			}
			set
			{
				this._mesnogir = value;
			}
		}
		
		private byte? _diavtoat;
		public virtual byte? Diavtoat
		{
			get
			{
				return this._diavtoat;
			}
			set
			{
				this._diavtoat = value;
			}
		}
		
		private ushort _codtarif;
		public virtual ushort Codtarif
		{
			get
			{
				return this._codtarif;
			}
			set
			{
				this._codtarif = value;
			}
		}
		
		private decimal _dtoppago;
		public virtual decimal Dtoppago
		{
			get
			{
				return this._dtoppago;
			}
			set
			{
				this._dtoppago = value;
			}
		}
		
		private decimal _dtognral;
		public virtual decimal Dtognral
		{
			get
			{
				return this._dtognral;
			}
			set
			{
				this._dtognral = value;
			}
		}
		
		private byte _promocio;
		public virtual byte Promocio
		{
			get
			{
				return this._promocio;
			}
			set
			{
				this._promocio = value;
			}
		}
		
		private ushort _codsitua;
		public virtual ushort Codsitua
		{
			get
			{
				return this._codsitua;
			}
			set
			{
				this._codsitua = value;
			}
		}
		
		private byte _referobl;
		public virtual byte Referobl
		{
			get
			{
				return this._referobl;
			}
			set
			{
				this._referobl = value;
			}
		}
		
		private byte _cliabono;
		public virtual byte Cliabono
		{
			get
			{
				return this._cliabono;
			}
			set
			{
				this._cliabono = value;
			}
		}
		
		private ushort? _kilometr;
		public virtual ushort? Kilometr
		{
			get
			{
				return this._kilometr;
			}
			set
			{
				this._kilometr = value;
			}
		}
		
		private decimal? _limcredi;
		public virtual decimal? Limcredi
		{
			get
			{
				return this._limcredi;
			}
			set
			{
				this._limcredi = value;
			}
		}
		
		private DateTime? _fechaulr;
		public virtual DateTime? Fechaulr
		{
			get
			{
				return this._fechaulr;
			}
			set
			{
				this._fechaulr = value;
			}
		}
		
		private string _pasclien;
		public virtual string Pasclien
		{
			get
			{
				return this._pasclien;
			}
			set
			{
				this._pasclien = value;
			}
		}
		
		private string _observac;
		public virtual string Observac
		{
			get
			{
				return this._observac;
			}
			set
			{
				this._observac = value;
			}
		}
		
		private short _tasareciclado;
		public virtual short Tasareciclado
		{
			get
			{
				return this._tasareciclado;
			}
			set
			{
				this._tasareciclado = value;
			}
		}
		
		private short? _enviocorreo;
		public virtual short? Enviocorreo
		{
			get
			{
				return this._enviocorreo;
			}
			set
			{
				this._enviocorreo = value;
			}
		}
		
		private decimal? _gasAdm;
		public virtual decimal? GasAdm
		{
			get
			{
				return this._gasAdm;
			}
			set
			{
				this._gasAdm = value;
			}
		}
		
		private string _observa1;
		public virtual string Observa1
		{
			get
			{
				return this._observa1;
			}
			set
			{
				this._observa1 = value;
			}
		}
		
		private string _organoGestor;
		public virtual string OrganoGestor
		{
			get
			{
				return this._organoGestor;
			}
			set
			{
				this._organoGestor = value;
			}
		}
		
		private string _unidadTramitadora;
		public virtual string UnidadTramitadora
		{
			get
			{
				return this._unidadTramitadora;
			}
			set
			{
				this._unidadTramitadora = value;
			}
		}
		
		private string _oficinaContable;
		public virtual string OficinaContable
		{
			get
			{
				return this._oficinaContable;
			}
			set
			{
				this._oficinaContable = value;
			}
		}
		
		private string _organoProponente;
		public virtual string OrganoProponente
		{
			get
			{
				return this._organoProponente;
			}
			set
			{
				this._organoProponente = value;
			}
		}
		
		private short _codbanpr;
		public virtual short Codbanpr
		{
			get
			{
				return this._codbanpr;
			}
			set
			{
				this._codbanpr = value;
			}
		}
		
		private string _organogestor;
		public virtual string Organogestor
		{
			get
			{
				return this._organogestor;
			}
			set
			{
				this._organogestor = value;
			}
		}
		
		private string _unidadtramitadora;
		public virtual string Unidadtramitadora
		{
			get
			{
				return this._unidadtramitadora;
			}
			set
			{
				this._unidadtramitadora = value;
			}
		}
		
		private string _oficinacontable;
		public virtual string Oficinacontable
		{
			get
			{
				return this._oficinacontable;
			}
			set
			{
				this._oficinacontable = value;
			}
		}
		
		private string _orgproponente;
		public virtual string Orgproponente
		{
			get
			{
				return this._orgproponente;
			}
			set
			{
				this._orgproponente = value;
			}
		}
		
		private string _iban;
		public virtual string Iban
		{
			get
			{
				return this._iban;
			}
			set
			{
				this._iban = value;
			}
		}
		
		private Sbanpr _sbanpr;
		public virtual Sbanpr Sbanpr
		{
			get
			{
				return this._sbanpr;
			}
			set
			{
				this._sbanpr = value;
			}
		}
		
		private IList<Scafaccli> _scafacclis = new List<Scafaccli>();
		public virtual IList<Scafaccli> Scafacclis
		{
			get
			{
				return this._scafacclis;
			}
		}
		
	}
}
#pragma warning restore 1591
