#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriTaxiModel;

namespace AriTaxiModel	
{
	public partial class Sfactusoc
	{
		private string _codtipom;
		public virtual string Codtipom
		{
			get
			{
				return this._codtipom;
			}
			set
			{
				this._codtipom = value;
			}
		}
		
		private uint _codsocio;
		public virtual uint Codsocio
		{
			get
			{
				return this._codsocio;
			}
			set
			{
				this._codsocio = value;
			}
		}
		
		private uint _numfactu;
		public virtual uint Numfactu
		{
			get
			{
				return this._numfactu;
			}
			set
			{
				this._numfactu = value;
			}
		}
		
		private DateTime _fecfactu;
		public virtual DateTime Fecfactu
		{
			get
			{
				return this._fecfactu;
			}
			set
			{
				this._fecfactu = value;
			}
		}
		
		private string _concepto;
		public virtual string Concepto
		{
			get
			{
				return this._concepto;
			}
			set
			{
				this._concepto = value;
			}
		}
		
		private decimal _importel;
		public virtual decimal Importel
		{
			get
			{
				return this._importel;
			}
			set
			{
				this._importel = value;
			}
		}
		
		private decimal _baseiva1;
		public virtual decimal Baseiva1
		{
			get
			{
				return this._baseiva1;
			}
			set
			{
				this._baseiva1 = value;
			}
		}
		
		private decimal _impoiva1;
		public virtual decimal Impoiva1
		{
			get
			{
				return this._impoiva1;
			}
			set
			{
				this._impoiva1 = value;
			}
		}
		
		private short _codiiva1;
		public virtual short Codiiva1
		{
			get
			{
				return this._codiiva1;
			}
			set
			{
				this._codiiva1 = value;
			}
		}
		
		private decimal _porciva1;
		public virtual decimal Porciva1
		{
			get
			{
				return this._porciva1;
			}
			set
			{
				this._porciva1 = value;
			}
		}
		
		private decimal? _basereten;
		public virtual decimal? Basereten
		{
			get
			{
				return this._basereten;
			}
			set
			{
				this._basereten = value;
			}
		}
		
		private decimal? _porcreten;
		public virtual decimal? Porcreten
		{
			get
			{
				return this._porcreten;
			}
			set
			{
				this._porcreten = value;
			}
		}
		
		private decimal _totalfac;
		public virtual decimal Totalfac
		{
			get
			{
				return this._totalfac;
			}
			set
			{
				this._totalfac = value;
			}
		}
		
		private decimal? _impreten;
		public virtual decimal? Impreten
		{
			get
			{
				return this._impreten;
			}
			set
			{
				this._impreten = value;
			}
		}
		
		private short _intconta;
		public virtual short Intconta
		{
			get
			{
				return this._intconta;
			}
			set
			{
				this._intconta = value;
			}
		}
		
		private ushort _codforpa;
		public virtual ushort Codforpa
		{
			get
			{
				return this._codforpa;
			}
			set
			{
				this._codforpa = value;
			}
		}
		
		private uint _numeruve;
		public virtual uint Numeruve
		{
			get
			{
				return this._numeruve;
			}
			set
			{
				this._numeruve = value;
			}
		}
		
		private int? _numserv;
		public virtual int? Numserv
		{
			get
			{
				return this._numserv;
			}
			set
			{
				this._numserv = value;
			}
		}
		
		private byte _exportada;
		public virtual byte Exportada
		{
			get
			{
				return this._exportada;
			}
			set
			{
				this._exportada = value;
			}
		}
		
		private Sclien _sclien;
		public virtual Sclien Sclien
		{
			get
			{
				return this._sclien;
			}
			set
			{
				this._sclien = value;
			}
		}
		
	}
}
#pragma warning restore 1591
