#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriTaxiModel;

namespace AriTaxiModel	
{
	public partial class Sforpa
	{
		private ushort _codforpa;
		public virtual ushort Codforpa
		{
			get
			{
				return this._codforpa;
			}
			set
			{
				this._codforpa = value;
			}
		}
		
		private string _nomforpa;
		public virtual string Nomforpa
		{
			get
			{
				return this._nomforpa;
			}
			set
			{
				this._nomforpa = value;
			}
		}
		
		private ushort _tipforpa;
		public virtual ushort Tipforpa
		{
			get
			{
				return this._tipforpa;
			}
			set
			{
				this._tipforpa = value;
			}
		}
		
		private IList<Scliente> _sclientes = new List<Scliente>();
		public virtual IList<Scliente> Sclientes
		{
			get
			{
				return this._sclientes;
			}
		}
		
	}
}
#pragma warning restore 1591
