#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace AriTaxiModel	
{
	public partial class Slifaccli
	{
		private string _codtipom;
		public virtual string Codtipom
		{
			get
			{
				return this._codtipom;
			}
			set
			{
				this._codtipom = value;
			}
		}
		
		private uint _numfactu;
		public virtual uint Numfactu
		{
			get
			{
				return this._numfactu;
			}
			set
			{
				this._numfactu = value;
			}
		}
		
		private DateTime _fecfactu;
		public virtual DateTime Fecfactu
		{
			get
			{
				return this._fecfactu;
			}
			set
			{
				this._fecfactu = value;
			}
		}
		
		private string _codtipoa;
		public virtual string Codtipoa
		{
			get
			{
				return this._codtipoa;
			}
			set
			{
				this._codtipoa = value;
			}
		}
		
		private uint _numalbar;
		public virtual uint Numalbar
		{
			get
			{
				return this._numalbar;
			}
			set
			{
				this._numalbar = value;
			}
		}
		
		private ushort _numlinea;
		public virtual ushort Numlinea
		{
			get
			{
				return this._numlinea;
			}
			set
			{
				this._numlinea = value;
			}
		}
		
		private ushort _codalmac;
		public virtual ushort Codalmac
		{
			get
			{
				return this._codalmac;
			}
			set
			{
				this._codalmac = value;
			}
		}
		
		private string _codartic;
		public virtual string Codartic
		{
			get
			{
				return this._codartic;
			}
			set
			{
				this._codartic = value;
			}
		}
		
		private string _nomartic;
		public virtual string Nomartic
		{
			get
			{
				return this._nomartic;
			}
			set
			{
				this._nomartic = value;
			}
		}
		
		private string _ampliaci;
		public virtual string Ampliaci
		{
			get
			{
				return this._ampliaci;
			}
			set
			{
				this._ampliaci = value;
			}
		}
		
		private decimal? _cantidad;
		public virtual decimal? Cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				this._cantidad = value;
			}
		}
		
		private int _numbultos;
		public virtual int Numbultos
		{
			get
			{
				return this._numbultos;
			}
			set
			{
				this._numbultos = value;
			}
		}
		
		private decimal? _precioar;
		public virtual decimal? Precioar
		{
			get
			{
				return this._precioar;
			}
			set
			{
				this._precioar = value;
			}
		}
		
		private decimal _dtoline1;
		public virtual decimal Dtoline1
		{
			get
			{
				return this._dtoline1;
			}
			set
			{
				this._dtoline1 = value;
			}
		}
		
		private decimal _dtoline2;
		public virtual decimal Dtoline2
		{
			get
			{
				return this._dtoline2;
			}
			set
			{
				this._dtoline2 = value;
			}
		}
		
		private decimal? _importel;
		public virtual decimal? Importel
		{
			get
			{
				return this._importel;
			}
			set
			{
				this._importel = value;
			}
		}
		
		private Char _origpre;
		public virtual Char Origpre
		{
			get
			{
				return this._origpre;
			}
			set
			{
				this._origpre = value;
			}
		}
		
		private decimal? _precioiv;
		public virtual decimal? Precioiv
		{
			get
			{
				return this._precioiv;
			}
			set
			{
				this._precioiv = value;
			}
		}
		
		private decimal? _preciomp;
		public virtual decimal? Preciomp
		{
			get
			{
				return this._preciomp;
			}
			set
			{
				this._preciomp = value;
			}
		}
		
		private decimal? _preciost;
		public virtual decimal? Preciost
		{
			get
			{
				return this._preciost;
			}
			set
			{
				this._preciost = value;
			}
		}
		
		private decimal? _preciouc;
		public virtual decimal? Preciouc
		{
			get
			{
				return this._preciouc;
			}
			set
			{
				this._preciouc = value;
			}
		}
		
		private int _codproveX;
		public virtual int CodproveX
		{
			get
			{
				return this._codproveX;
			}
			set
			{
				this._codproveX = value;
			}
		}
		
		private string _numlote;
		public virtual string Numlote
		{
			get
			{
				return this._numlote;
			}
			set
			{
				this._numlote = value;
			}
		}
		
		private string _codccost;
		public virtual string Codccost
		{
			get
			{
				return this._codccost;
			}
			set
			{
				this._codccost = value;
			}
		}
		
	}
}
#pragma warning restore 1591
