#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace AriTaxiModel	
{
	public partial class SparamTaxi
	{
		private byte _codigo;
		public virtual byte Codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				this._codigo = value;
			}
		}
		
		private string _nomempre;
		public virtual string Nomempre
		{
			get
			{
				return this._nomempre;
			}
			set
			{
				this._nomempre = value;
			}
		}
		
		private string _domempre;
		public virtual string Domempre
		{
			get
			{
				return this._domempre;
			}
			set
			{
				this._domempre = value;
			}
		}
		
		private string _codpobla;
		public virtual string Codpobla
		{
			get
			{
				return this._codpobla;
			}
			set
			{
				this._codpobla = value;
			}
		}
		
		private string _pobempre;
		public virtual string Pobempre
		{
			get
			{
				return this._pobempre;
			}
			set
			{
				this._pobempre = value;
			}
		}
		
		private string _proempre;
		public virtual string Proempre
		{
			get
			{
				return this._proempre;
			}
			set
			{
				this._proempre = value;
			}
		}
		
		private string _cifempre;
		public virtual string Cifempre
		{
			get
			{
				return this._cifempre;
			}
			set
			{
				this._cifempre = value;
			}
		}
		
		private string _telempre;
		public virtual string Telempre
		{
			get
			{
				return this._telempre;
			}
			set
			{
				this._telempre = value;
			}
		}
		
		private string _faxempre;
		public virtual string Faxempre
		{
			get
			{
				return this._faxempre;
			}
			set
			{
				this._faxempre = value;
			}
		}
		
		private string _wwwempre;
		public virtual string Wwwempre
		{
			get
			{
				return this._wwwempre;
			}
			set
			{
				this._wwwempre = value;
			}
		}
		
		private string _maiempre;
		public virtual string Maiempre
		{
			get
			{
				return this._maiempre;
			}
			set
			{
				this._maiempre = value;
			}
		}
		
	}
}
#pragma warning restore 1591
