#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace AriTaxiModel	
{
	public partial class StipomTaxi
	{
		private string _codtipom;
		public virtual string Codtipom
		{
			get
			{
				return this._codtipom;
			}
			set
			{
				this._codtipom = value;
			}
		}
		
		private string _nomtipom;
		public virtual string Nomtipom
		{
			get
			{
				return this._nomtipom;
			}
			set
			{
				this._nomtipom = value;
			}
		}
		
		private byte _muevesto;
		public virtual byte Muevesto
		{
			get
			{
				return this._muevesto;
			}
			set
			{
				this._muevesto = value;
			}
		}
		
		private int _contador;
		public virtual int Contador
		{
			get
			{
				return this._contador;
			}
			set
			{
				this._contador = value;
			}
		}
		
		private string _letraser;
		public virtual string Letraser
		{
			get
			{
				return this._letraser;
			}
			set
			{
				this._letraser = value;
			}
		}
		
		private byte? _tipodocu;
		public virtual byte? Tipodocu
		{
			get
			{
				return this._tipodocu;
			}
			set
			{
				this._tipodocu = value;
			}
		}
		
	}
}
#pragma warning restore 1591
