#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriTaxiModel;

namespace AriTaxiModel	
{
	public partial class Svencicli
	{
		private string _codtipom;
		public virtual string Codtipom
		{
			get
			{
				return this._codtipom;
			}
			set
			{
				this._codtipom = value;
			}
		}
		
		private uint _numfacu;
		public virtual uint Numfacu
		{
			get
			{
				return this._numfacu;
			}
			set
			{
				this._numfacu = value;
			}
		}
		
		private DateTime _fecfactu;
		public virtual DateTime Fecfactu
		{
			get
			{
				return this._fecfactu;
			}
			set
			{
				this._fecfactu = value;
			}
		}
		
		private ushort _ordefect;
		public virtual ushort Ordefect
		{
			get
			{
				return this._ordefect;
			}
			set
			{
				this._ordefect = value;
			}
		}
		
		private DateTime _fecefect;
		public virtual DateTime Fecefect
		{
			get
			{
				return this._fecefect;
			}
			set
			{
				this._fecefect = value;
			}
		}
		
		private decimal _impefect;
		public virtual decimal Impefect
		{
			get
			{
				return this._impefect;
			}
			set
			{
				this._impefect = value;
			}
		}
		
		private Scafaccli _scafaccli;
		public virtual Scafaccli Scafaccli
		{
			get
			{
				return this._scafaccli;
			}
			set
			{
				this._scafaccli = value;
			}
		}
		
	}
}
#pragma warning restore 1591
