#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriAgroModel;

namespace AriAgroModel	
{
	public partial class Cliente
	{
		private uint _codclien;
		public virtual uint Codclien
		{
			get
			{
				return this._codclien;
			}
			set
			{
				this._codclien = value;
			}
		}
		
		private string _nomclien;
		public virtual string Nomclien
		{
			get
			{
				return this._nomclien;
			}
			set
			{
				this._nomclien = value;
			}
		}
		
		private string _domclien;
		public virtual string Domclien
		{
			get
			{
				return this._domclien;
			}
			set
			{
				this._domclien = value;
			}
		}
		
		private string _codpobla;
		public virtual string Codpobla
		{
			get
			{
				return this._codpobla;
			}
			set
			{
				this._codpobla = value;
			}
		}
		
		private string _pobclien;
		public virtual string Pobclien
		{
			get
			{
				return this._pobclien;
			}
			set
			{
				this._pobclien = value;
			}
		}
		
		private string _proclien;
		public virtual string Proclien
		{
			get
			{
				return this._proclien;
			}
			set
			{
				this._proclien = value;
			}
		}
		
		private ushort? _codpaise;
		public virtual ushort? Codpaise
		{
			get
			{
				return this._codpaise;
			}
			set
			{
				this._codpaise = value;
			}
		}
		
		private string _wwwclien;
		public virtual string Wwwclien
		{
			get
			{
				return this._wwwclien;
			}
			set
			{
				this._wwwclien = value;
			}
		}
		
		private string _cifclien;
		public virtual string Cifclien
		{
			get
			{
				return this._cifclien;
			}
			set
			{
				this._cifclien = value;
			}
		}
		
		private string _telclie1;
		public virtual string Telclie1
		{
			get
			{
				return this._telclie1;
			}
			set
			{
				this._telclie1 = value;
			}
		}
		
		private string _faxclie1;
		public virtual string Faxclie1
		{
			get
			{
				return this._faxclie1;
			}
			set
			{
				this._faxclie1 = value;
			}
		}
		
		private string _movclie1;
		public virtual string Movclie1
		{
			get
			{
				return this._movclie1;
			}
			set
			{
				this._movclie1 = value;
			}
		}
		
		private string _maiclie1;
		public virtual string Maiclie1
		{
			get
			{
				return this._maiclie1;
			}
			set
			{
				this._maiclie1 = value;
			}
		}
		
		private string _perclie1;
		public virtual string Perclie1
		{
			get
			{
				return this._perclie1;
			}
			set
			{
				this._perclie1 = value;
			}
		}
		
		private string _telclie2;
		public virtual string Telclie2
		{
			get
			{
				return this._telclie2;
			}
			set
			{
				this._telclie2 = value;
			}
		}
		
		private string _faxclie2;
		public virtual string Faxclie2
		{
			get
			{
				return this._faxclie2;
			}
			set
			{
				this._faxclie2 = value;
			}
		}
		
		private string _movclie2;
		public virtual string Movclie2
		{
			get
			{
				return this._movclie2;
			}
			set
			{
				this._movclie2 = value;
			}
		}
		
		private string _maiclie2;
		public virtual string Maiclie2
		{
			get
			{
				return this._maiclie2;
			}
			set
			{
				this._maiclie2 = value;
			}
		}
		
		private string _perclie2;
		public virtual string Perclie2
		{
			get
			{
				return this._perclie2;
			}
			set
			{
				this._perclie2 = value;
			}
		}
		
		private string _observac;
		public virtual string Observac
		{
			get
			{
				return this._observac;
			}
			set
			{
				this._observac = value;
			}
		}
		
		private ushort _codforpa;
		public virtual ushort Codforpa
		{
			get
			{
				return this._codforpa;
			}
			set
			{
				this._codforpa = value;
			}
		}
		
		private short _tipoiva;
		public virtual short Tipoiva
		{
			get
			{
				return this._tipoiva;
			}
			set
			{
				this._tipoiva = value;
			}
		}
		
		private decimal? _porccom1;
		public virtual decimal? Porccom1
		{
			get
			{
				return this._porccom1;
			}
			set
			{
				this._porccom1 = value;
			}
		}
		
		private decimal? _porccom2;
		public virtual decimal? Porccom2
		{
			get
			{
				return this._porccom2;
			}
			set
			{
				this._porccom2 = value;
			}
		}
		
		private byte _tipodtos;
		public virtual byte Tipodtos
		{
			get
			{
				return this._tipodtos;
			}
			set
			{
				this._tipodtos = value;
			}
		}
		
		private string _codmacta;
		public virtual string Codmacta
		{
			get
			{
				return this._codmacta;
			}
			set
			{
				this._codmacta = value;
			}
		}
		
		private byte _cliabono;
		public virtual byte Cliabono
		{
			get
			{
				return this._cliabono;
			}
			set
			{
				this._cliabono = value;
			}
		}
		
		private byte _tipofact;
		public virtual byte Tipofact
		{
			get
			{
				return this._tipofact;
			}
			set
			{
				this._tipofact = value;
			}
		}
		
		private string _codtipom;
		public virtual string Codtipom
		{
			get
			{
				return this._codtipom;
			}
			set
			{
				this._codtipom = value;
			}
		}
		
		private ushort? _codbanco;
		public virtual ushort? Codbanco
		{
			get
			{
				return this._codbanco;
			}
			set
			{
				this._codbanco = value;
			}
		}
		
		private ushort? _codsucur;
		public virtual ushort? Codsucur
		{
			get
			{
				return this._codsucur;
			}
			set
			{
				this._codsucur = value;
			}
		}
		
		private string _digcontr;
		public virtual string Digcontr
		{
			get
			{
				return this._digcontr;
			}
			set
			{
				this._digcontr = value;
			}
		}
		
		private string _cuentaba;
		public virtual string Cuentaba
		{
			get
			{
				return this._cuentaba;
			}
			set
			{
				this._cuentaba = value;
			}
		}
		
		private string _codigoedi;
		public virtual string Codigoedi
		{
			get
			{
				return this._codigoedi;
			}
			set
			{
				this._codigoedi = value;
			}
		}
		
		private ushort _nrocopias;
		public virtual ushort Nrocopias
		{
			get
			{
				return this._nrocopias;
			}
			set
			{
				this._nrocopias = value;
			}
		}
		
		private short _nrodecprec;
		public virtual short Nrodecprec
		{
			get
			{
				return this._nrodecprec;
			}
			set
			{
				this._nrodecprec = value;
			}
		}
		
		private short _destedi;
		public virtual short Destedi
		{
			get
			{
				return this._destedi;
			}
			set
			{
				this._destedi = value;
			}
		}
		
		private byte _ctrolcobroalb;
		public virtual byte Ctrolcobroalb
		{
			get
			{
				return this._ctrolcobroalb;
			}
			set
			{
				this._ctrolcobroalb = value;
			}
		}
		
		private string _nroseguro;
		public virtual string Nroseguro
		{
			get
			{
				return this._nroseguro;
			}
			set
			{
				this._nroseguro = value;
			}
		}
		
		private short? _diasasegurados;
		public virtual short? Diasasegurados
		{
			get
			{
				return this._diasasegurados;
			}
			set
			{
				this._diasasegurados = value;
			}
		}
		
		private decimal? _limiteriesgos;
		public virtual decimal? Limiteriesgos
		{
			get
			{
				return this._limiteriesgos;
			}
			set
			{
				this._limiteriesgos = value;
			}
		}
		
		private string _domcliencorreo;
		public virtual string Domcliencorreo
		{
			get
			{
				return this._domcliencorreo;
			}
			set
			{
				this._domcliencorreo = value;
			}
		}
		
		private string _pobcliencorreo;
		public virtual string Pobcliencorreo
		{
			get
			{
				return this._pobcliencorreo;
			}
			set
			{
				this._pobcliencorreo = value;
			}
		}
		
		private string _procliencorreo;
		public virtual string Procliencorreo
		{
			get
			{
				return this._procliencorreo;
			}
			set
			{
				this._procliencorreo = value;
			}
		}
		
		private string _codpoblacorreo;
		public virtual string Codpoblacorreo
		{
			get
			{
				return this._codpoblacorreo;
			}
			set
			{
				this._codpoblacorreo = value;
			}
		}
		
		private string _codtipalb;
		public virtual string Codtipalb
		{
			get
			{
				return this._codtipalb;
			}
			set
			{
				this._codtipalb = value;
			}
		}
		
		private IList<Factura> _facturas = new List<Factura>();
		public virtual IList<Factura> Facturas
		{
			get
			{
				return this._facturas;
			}
		}
		
	}
}
#pragma warning restore 1591
