#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriAgroModel;

namespace AriAgroModel	
{
	public partial class AriAgroCtx : OpenAccessContext, IAriAgroCtxUnitOfWork
	{
		private static string connectionStringName = @"Ariagro4Connection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel1.rlinq");
		
		public AriAgroCtx()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public AriAgroCtx(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public AriAgroCtx(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public AriAgroCtx(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public AriAgroCtx(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Factura> Facturas 
		{
			get
			{
				return this.GetAll<Factura>();
			}
		}
		
		public IQueryable<Cliente> Clientes 
		{
			get
			{
				return this.GetAll<Cliente>();
			}
		}
		
		public IQueryable<Empresa> Empresas 
		{
			get
			{
				return this.GetAll<Empresa>();
			}
		}
		
		public IQueryable<Rsocio> Rsocios 
		{
			get
			{
				return this.GetAll<Rsocio>();
			}
		}
		
		public IQueryable<Rfactsoc> Rfactsocs 
		{
			get
			{
				return this.GetAll<Rfactsoc>();
			}
		}
		
		public IQueryable<Rcampo> Rcampos 
		{
			get
			{
				return this.GetAll<Rcampo>();
			}
		}
		
		public IQueryable<Variedade> Variedades 
		{
			get
			{
				return this.GetAll<Variedade>();
			}
		}
		
		public IQueryable<Rsituacioncampo> Rsituacioncampos 
		{
			get
			{
				return this.GetAll<Rsituacioncampo>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
			return backend;
		}
	}
	
	public interface IAriAgroCtxUnitOfWork : IUnitOfWork
	{
		IQueryable<Factura> Facturas
		{
			get;
		}
		IQueryable<Cliente> Clientes
		{
			get;
		}
		IQueryable<Empresa> Empresas
		{
			get;
		}
		IQueryable<Rsocio> Rsocios
		{
			get;
		}
		IQueryable<Rfactsoc> Rfactsocs
		{
			get;
		}
		IQueryable<Rcampo> Rcampos
		{
			get;
		}
		IQueryable<Variedade> Variedades
		{
			get;
		}
		IQueryable<Rsituacioncampo> Rsituacioncampos
		{
			get;
		}
	}
}
#pragma warning restore 1591
