#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriAgroModel;

namespace AriAgroModel	
{
	public partial class Factura
	{
		private string _codtipom;
		public virtual string Codtipom
		{
			get
			{
				return this._codtipom;
			}
			set
			{
				this._codtipom = value;
			}
		}
		
		private uint _numfactu;
		public virtual uint Numfactu
		{
			get
			{
				return this._numfactu;
			}
			set
			{
				this._numfactu = value;
			}
		}
		
		private DateTime _fecfactu;
		public virtual DateTime Fecfactu
		{
			get
			{
				return this._fecfactu;
			}
			set
			{
				this._fecfactu = value;
			}
		}
		
		private uint _codclien;
		public virtual uint Codclien
		{
			get
			{
				return this._codclien;
			}
			set
			{
				this._codclien = value;
			}
		}
		
		private ushort _codforpa;
		public virtual ushort Codforpa
		{
			get
			{
				return this._codforpa;
			}
			set
			{
				this._codforpa = value;
			}
		}
		
		private short _tipoivac;
		public virtual short Tipoivac
		{
			get
			{
				return this._tipoivac;
			}
			set
			{
				this._tipoivac = value;
			}
		}
		
		private decimal? _dtocom1;
		public virtual decimal? Dtocom1
		{
			get
			{
				return this._dtocom1;
			}
			set
			{
				this._dtocom1 = value;
			}
		}
		
		private decimal? _dtocom2;
		public virtual decimal? Dtocom2
		{
			get
			{
				return this._dtocom2;
			}
			set
			{
				this._dtocom2 = value;
			}
		}
		
		private decimal? _impdtoc;
		public virtual decimal? Impdtoc
		{
			get
			{
				return this._impdtoc;
			}
			set
			{
				this._impdtoc = value;
			}
		}
		
		private string _observac;
		public virtual string Observac
		{
			get
			{
				return this._observac;
			}
			set
			{
				this._observac = value;
			}
		}
		
		private decimal? _baseimp1;
		public virtual decimal? Baseimp1
		{
			get
			{
				return this._baseimp1;
			}
			set
			{
				this._baseimp1 = value;
			}
		}
		
		private decimal? _baseimp2;
		public virtual decimal? Baseimp2
		{
			get
			{
				return this._baseimp2;
			}
			set
			{
				this._baseimp2 = value;
			}
		}
		
		private decimal? _baseimp3;
		public virtual decimal? Baseimp3
		{
			get
			{
				return this._baseimp3;
			}
			set
			{
				this._baseimp3 = value;
			}
		}
		
		private decimal? _impoiva1;
		public virtual decimal? Impoiva1
		{
			get
			{
				return this._impoiva1;
			}
			set
			{
				this._impoiva1 = value;
			}
		}
		
		private decimal? _impoiva2;
		public virtual decimal? Impoiva2
		{
			get
			{
				return this._impoiva2;
			}
			set
			{
				this._impoiva2 = value;
			}
		}
		
		private decimal? _impoiva3;
		public virtual decimal? Impoiva3
		{
			get
			{
				return this._impoiva3;
			}
			set
			{
				this._impoiva3 = value;
			}
		}
		
		private decimal? _imporec1;
		public virtual decimal? Imporec1
		{
			get
			{
				return this._imporec1;
			}
			set
			{
				this._imporec1 = value;
			}
		}
		
		private decimal? _imporec2;
		public virtual decimal? Imporec2
		{
			get
			{
				return this._imporec2;
			}
			set
			{
				this._imporec2 = value;
			}
		}
		
		private decimal? _imporec3;
		public virtual decimal? Imporec3
		{
			get
			{
				return this._imporec3;
			}
			set
			{
				this._imporec3 = value;
			}
		}
		
		private short? _codiiva1;
		public virtual short? Codiiva1
		{
			get
			{
				return this._codiiva1;
			}
			set
			{
				this._codiiva1 = value;
			}
		}
		
		private short? _codiiva2;
		public virtual short? Codiiva2
		{
			get
			{
				return this._codiiva2;
			}
			set
			{
				this._codiiva2 = value;
			}
		}
		
		private short? _codiiva3;
		public virtual short? Codiiva3
		{
			get
			{
				return this._codiiva3;
			}
			set
			{
				this._codiiva3 = value;
			}
		}
		
		private decimal? _porciva1;
		public virtual decimal? Porciva1
		{
			get
			{
				return this._porciva1;
			}
			set
			{
				this._porciva1 = value;
			}
		}
		
		private decimal? _porciva2;
		public virtual decimal? Porciva2
		{
			get
			{
				return this._porciva2;
			}
			set
			{
				this._porciva2 = value;
			}
		}
		
		private decimal? _porciva3;
		public virtual decimal? Porciva3
		{
			get
			{
				return this._porciva3;
			}
			set
			{
				this._porciva3 = value;
			}
		}
		
		private decimal? _porcrec1;
		public virtual decimal? Porcrec1
		{
			get
			{
				return this._porcrec1;
			}
			set
			{
				this._porcrec1 = value;
			}
		}
		
		private decimal? _porcrec2;
		public virtual decimal? Porcrec2
		{
			get
			{
				return this._porcrec2;
			}
			set
			{
				this._porcrec2 = value;
			}
		}
		
		private decimal? _porcrec3;
		public virtual decimal? Porcrec3
		{
			get
			{
				return this._porcrec3;
			}
			set
			{
				this._porcrec3 = value;
			}
		}
		
		private decimal? _brutofac;
		public virtual decimal? Brutofac
		{
			get
			{
				return this._brutofac;
			}
			set
			{
				this._brutofac = value;
			}
		}
		
		private decimal? _impordto;
		public virtual decimal? Impordto
		{
			get
			{
				return this._impordto;
			}
			set
			{
				this._impordto = value;
			}
		}
		
		private decimal? _totalfac;
		public virtual decimal? Totalfac
		{
			get
			{
				return this._totalfac;
			}
			set
			{
				this._totalfac = value;
			}
		}
		
		private short _intconta;
		public virtual short Intconta
		{
			get
			{
				return this._intconta;
			}
			set
			{
				this._intconta = value;
			}
		}
		
		private short _pasaridoc;
		public virtual short Pasaridoc
		{
			get
			{
				return this._pasaridoc;
			}
			set
			{
				this._pasaridoc = value;
			}
		}
		
		private short _pasedicom;
		public virtual short Pasedicom
		{
			get
			{
				return this._pasedicom;
			}
			set
			{
				this._pasedicom = value;
			}
		}
		
		private byte _enfacturae;
		public virtual byte Enfacturae
		{
			get
			{
				return this._enfacturae;
			}
			set
			{
				this._enfacturae = value;
			}
		}
		
		private Cliente _cliente;
		public virtual Cliente Cliente
		{
			get
			{
				return this._cliente;
			}
			set
			{
				this._cliente = value;
			}
		}
		
	}
}
#pragma warning restore 1591
