#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriAgroModel;

namespace AriAgroModel	
{
	public partial class Rcampo
	{
		private uint _codcampo;
		public virtual uint Codcampo
		{
			get
			{
				return this._codcampo;
			}
			set
			{
				this._codcampo = value;
			}
		}
		
		private uint _codsocio;
		public virtual uint Codsocio
		{
			get
			{
				return this._codsocio;
			}
			set
			{
				this._codsocio = value;
			}
		}
		
		private uint _codpropiet;
		public virtual uint Codpropiet
		{
			get
			{
				return this._codpropiet;
			}
			set
			{
				this._codpropiet = value;
			}
		}
		
		private uint _codvarie;
		public virtual uint Codvarie
		{
			get
			{
				return this._codvarie;
			}
			set
			{
				this._codvarie = value;
			}
		}
		
		private ushort _codparti;
		public virtual ushort Codparti
		{
			get
			{
				return this._codparti;
			}
			set
			{
				this._codparti = value;
			}
		}
		
		private DateTime _fecaltas;
		public virtual DateTime Fecaltas
		{
			get
			{
				return this._fecaltas;
			}
			set
			{
				this._fecaltas = value;
			}
		}
		
		private DateTime? _fecbajas;
		public virtual DateTime? Fecbajas
		{
			get
			{
				return this._fecbajas;
			}
			set
			{
				this._fecbajas = value;
			}
		}
		
		private short? _anoplant;
		public virtual short? Anoplant
		{
			get
			{
				return this._anoplant;
			}
			set
			{
				this._anoplant = value;
			}
		}
		
		private short? _nroarbol;
		public virtual short? Nroarbol
		{
			get
			{
				return this._nroarbol;
			}
			set
			{
				this._nroarbol = value;
			}
		}
		
		private decimal _supsigpa;
		public virtual decimal Supsigpa
		{
			get
			{
				return this._supsigpa;
			}
			set
			{
				this._supsigpa = value;
			}
		}
		
		private decimal _supcoope;
		public virtual decimal Supcoope
		{
			get
			{
				return this._supcoope;
			}
			set
			{
				this._supcoope = value;
			}
		}
		
		private decimal _supcatas;
		public virtual decimal Supcatas
		{
			get
			{
				return this._supcatas;
			}
			set
			{
				this._supcatas = value;
			}
		}
		
		private int? _canaforo;
		public virtual int? Canaforo
		{
			get
			{
				return this._canaforo;
			}
			set
			{
				this._canaforo = value;
			}
		}
		
		private ushort _codsitua;
		public virtual ushort Codsitua
		{
			get
			{
				return this._codsitua;
			}
			set
			{
				this._codsitua = value;
			}
		}
		
		private short _poligono;
		public virtual short Poligono
		{
			get
			{
				return this._poligono;
			}
			set
			{
				this._poligono = value;
			}
		}
		
		private int _parcela;
		public virtual int Parcela
		{
			get
			{
				return this._parcela;
			}
			set
			{
				this._parcela = value;
			}
		}
		
		private string _subparce;
		public virtual string Subparce
		{
			get
			{
				return this._subparce;
			}
			set
			{
				this._subparce = value;
			}
		}
		
		private short _asegurado;
		public virtual short Asegurado
		{
			get
			{
				return this._asegurado;
			}
			set
			{
				this._asegurado = value;
			}
		}
		
		private int? _kilosase;
		public virtual int? Kilosase
		{
			get
			{
				return this._kilosase;
			}
			set
			{
				this._kilosase = value;
			}
		}
		
		private short _tipoparc;
		public virtual short Tipoparc
		{
			get
			{
				return this._tipoparc;
			}
			set
			{
				this._tipoparc = value;
			}
		}
		
		private short _recintos;
		public virtual short Recintos
		{
			get
			{
				return this._recintos;
			}
			set
			{
				this._recintos = value;
			}
		}
		
		private int? _numeroid;
		public virtual int? Numeroid
		{
			get
			{
				return this._numeroid;
			}
			set
			{
				this._numeroid = value;
			}
		}
		
		private decimal? _latitud;
		public virtual decimal? Latitud
		{
			get
			{
				return this._latitud;
			}
			set
			{
				this._latitud = value;
			}
		}
		
		private decimal? _longitud;
		public virtual decimal? Longitud
		{
			get
			{
				return this._longitud;
			}
			set
			{
				this._longitud = value;
			}
		}
		
		private string _observac;
		public virtual string Observac
		{
			get
			{
				return this._observac;
			}
			set
			{
				this._observac = value;
			}
		}
		
		private int _nrocampo;
		public virtual int Nrocampo
		{
			get
			{
				return this._nrocampo;
			}
			set
			{
				this._nrocampo = value;
			}
		}
		
		private short _recolect;
		public virtual short Recolect
		{
			get
			{
				return this._recolect;
			}
			set
			{
				this._recolect = value;
			}
		}
		
		private ushort? _codtierra;
		public virtual ushort? Codtierra
		{
			get
			{
				return this._codtierra;
			}
			set
			{
				this._codtierra = value;
			}
		}
		
		private ushort? _codplanta;
		public virtual ushort? Codplanta
		{
			get
			{
				return this._codplanta;
			}
			set
			{
				this._codplanta = value;
			}
		}
		
		private ushort? _coddesa;
		public virtual ushort? Coddesa
		{
			get
			{
				return this._coddesa;
			}
			set
			{
				this._coddesa = value;
			}
		}
		
		private ushort? _codriego;
		public virtual ushort? Codriego
		{
			get
			{
				return this._codriego;
			}
			set
			{
				this._codriego = value;
			}
		}
		
		private ushort? _codcapat;
		public virtual ushort? Codcapat
		{
			get
			{
				return this._codcapat;
			}
			set
			{
				this._codcapat = value;
			}
		}
		
		private byte _pagounico;
		public virtual byte Pagounico
		{
			get
			{
				return this._pagounico;
			}
			set
			{
				this._pagounico = value;
			}
		}
		
		private byte _entregafichaculti;
		public virtual byte Entregafichaculti
		{
			get
			{
				return this._entregafichaculti;
			}
			set
			{
				this._entregafichaculti = value;
			}
		}
		
		private ushort? _codproce;
		public virtual ushort? Codproce
		{
			get
			{
				return this._codproce;
			}
			set
			{
				this._codproce = value;
			}
		}
		
		private ushort? _codpatron;
		public virtual ushort? Codpatron
		{
			get
			{
				return this._codpatron;
			}
			set
			{
				this._codpatron = value;
			}
		}
		
		private string _codseguro;
		public virtual string Codseguro
		{
			get
			{
				return this._codseguro;
			}
			set
			{
				this._codseguro = value;
			}
		}
		
		private short _conpoda;
		public virtual short Conpoda
		{
			get
			{
				return this._conpoda;
			}
			set
			{
				this._conpoda = value;
			}
		}
		
		private short _conresiduos;
		public virtual short Conresiduos
		{
			get
			{
				return this._conresiduos;
			}
			set
			{
				this._conresiduos = value;
			}
		}
		
		private int? _nrollave;
		public virtual int? Nrollave
		{
			get
			{
				return this._nrollave;
			}
			set
			{
				this._nrollave = value;
			}
		}
		
		private decimal? _costeseguro;
		public virtual decimal? Costeseguro
		{
			get
			{
				return this._costeseguro;
			}
			set
			{
				this._costeseguro = value;
			}
		}
		
		private decimal _supculti;
		public virtual decimal Supculti
		{
			get
			{
				return this._supculti;
			}
			set
			{
				this._supculti = value;
			}
		}
		
		private short? _tipocampo;
		public virtual short? Tipocampo
		{
			get
			{
				return this._tipocampo;
			}
			set
			{
				this._tipocampo = value;
			}
		}
		
		private string _codseguroant;
		public virtual string Codseguroant
		{
			get
			{
				return this._codseguroant;
			}
			set
			{
				this._codseguroant = value;
			}
		}
		
		private short _aseguradoant;
		public virtual short Aseguradoant
		{
			get
			{
				return this._aseguradoant;
			}
			set
			{
				this._aseguradoant = value;
			}
		}
		
		private int? _kilosaseant;
		public virtual int? Kilosaseant
		{
			get
			{
				return this._kilosaseant;
			}
			set
			{
				this._kilosaseant = value;
			}
		}
		
		private decimal? _costeseguroant;
		public virtual decimal? Costeseguroant
		{
			get
			{
				return this._costeseguroant;
			}
			set
			{
				this._costeseguroant = value;
			}
		}
		
		private ushort _codzonas;
		public virtual ushort Codzonas
		{
			get
			{
				return this._codzonas;
			}
			set
			{
				this._codzonas = value;
			}
		}
		
		private string _codigoggap;
		public virtual string Codigoggap
		{
			get
			{
				return this._codigoggap;
			}
			set
			{
				this._codigoggap = value;
			}
		}
		
		private uint? _codclien;
		public virtual uint? Codclien
		{
			get
			{
				return this._codclien;
			}
			set
			{
				this._codclien = value;
			}
		}
		
		private decimal? _dtoprecio;
		public virtual decimal? Dtoprecio
		{
			get
			{
				return this._dtoprecio;
			}
			set
			{
				this._dtoprecio = value;
			}
		}
		
		private string _refercatas;
		public virtual string Refercatas
		{
			get
			{
				return this._refercatas;
			}
			set
			{
				this._refercatas = value;
			}
		}
		
		private short? _esnaturane;
		public virtual short? Esnaturane
		{
			get
			{
				return this._esnaturane;
			}
			set
			{
				this._esnaturane = value;
			}
		}
		
		private short? _acabadorecol;
		public virtual short? Acabadorecol
		{
			get
			{
				return this._acabadorecol;
			}
			set
			{
				this._acabadorecol = value;
			}
		}
		
		private Rsocio _rsocio;
		public virtual Rsocio Rsocio
		{
			get
			{
				return this._rsocio;
			}
			set
			{
				this._rsocio = value;
			}
		}
		
		private Rsocio _rsocio1;
		public virtual Rsocio Rsocio1
		{
			get
			{
				return this._rsocio1;
			}
			set
			{
				this._rsocio1 = value;
			}
		}
		
		private Rsituacioncampo _rsituacioncampo;
		public virtual Rsituacioncampo Rsituacioncampo
		{
			get
			{
				return this._rsituacioncampo;
			}
			set
			{
				this._rsituacioncampo = value;
			}
		}
		
	}
}
#pragma warning restore 1591
