#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace AriAgroModel	
{
	public partial class Rsituacioncampo
	{
		private ushort _codsitua;
		public virtual ushort Codsitua
		{
			get
			{
				return this._codsitua;
			}
			set
			{
				this._codsitua = value;
			}
		}
		
		private string _nomsitua;
		public virtual string Nomsitua
		{
			get
			{
				return this._nomsitua;
			}
			set
			{
				this._nomsitua = value;
			}
		}
		
	}
}
#pragma warning restore 1591
