#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AriAgroModel;

namespace AriAgroModel	
{
	public partial class Rsocio
	{
		private uint _codsocio;
		public virtual uint Codsocio
		{
			get
			{
				return this._codsocio;
			}
			set
			{
				this._codsocio = value;
			}
		}
		
		private string _nifsocio;
		public virtual string Nifsocio
		{
			get
			{
				return this._nifsocio;
			}
			set
			{
				this._nifsocio = value;
			}
		}
		
		private string _nomsocio;
		public virtual string Nomsocio
		{
			get
			{
				return this._nomsocio;
			}
			set
			{
				this._nomsocio = value;
			}
		}
		
		private string _dirsocio;
		public virtual string Dirsocio
		{
			get
			{
				return this._dirsocio;
			}
			set
			{
				this._dirsocio = value;
			}
		}
		
		private string _pobsocio;
		public virtual string Pobsocio
		{
			get
			{
				return this._pobsocio;
			}
			set
			{
				this._pobsocio = value;
			}
		}
		
		private string _prosocio;
		public virtual string Prosocio
		{
			get
			{
				return this._prosocio;
			}
			set
			{
				this._prosocio = value;
			}
		}
		
		private string _codpostal;
		public virtual string Codpostal
		{
			get
			{
				return this._codpostal;
			}
			set
			{
				this._codpostal = value;
			}
		}
		
		private DateTime? _fechanac;
		public virtual DateTime? Fechanac
		{
			get
			{
				return this._fechanac;
			}
			set
			{
				this._fechanac = value;
			}
		}
		
		private string _telsoci1;
		public virtual string Telsoci1
		{
			get
			{
				return this._telsoci1;
			}
			set
			{
				this._telsoci1 = value;
			}
		}
		
		private string _telsoci2;
		public virtual string Telsoci2
		{
			get
			{
				return this._telsoci2;
			}
			set
			{
				this._telsoci2 = value;
			}
		}
		
		private string _telsoci3;
		public virtual string Telsoci3
		{
			get
			{
				return this._telsoci3;
			}
			set
			{
				this._telsoci3 = value;
			}
		}
		
		private string _movsocio;
		public virtual string Movsocio
		{
			get
			{
				return this._movsocio;
			}
			set
			{
				this._movsocio = value;
			}
		}
		
		private string _maisocio;
		public virtual string Maisocio
		{
			get
			{
				return this._maisocio;
			}
			set
			{
				this._maisocio = value;
			}
		}
		
		private ushort _codcoope;
		public virtual ushort Codcoope
		{
			get
			{
				return this._codcoope;
			}
			set
			{
				this._codcoope = value;
			}
		}
		
		private short? _codbanco;
		public virtual short? Codbanco
		{
			get
			{
				return this._codbanco;
			}
			set
			{
				this._codbanco = value;
			}
		}
		
		private short? _codsucur;
		public virtual short? Codsucur
		{
			get
			{
				return this._codsucur;
			}
			set
			{
				this._codsucur = value;
			}
		}
		
		private string _digcontr;
		public virtual string Digcontr
		{
			get
			{
				return this._digcontr;
			}
			set
			{
				this._digcontr = value;
			}
		}
		
		private string _cuentaba;
		public virtual string Cuentaba
		{
			get
			{
				return this._cuentaba;
			}
			set
			{
				this._cuentaba = value;
			}
		}
		
		private string _observaciones;
		public virtual string Observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				this._observaciones = value;
			}
		}
		
		private DateTime _fechaalta;
		public virtual DateTime Fechaalta
		{
			get
			{
				return this._fechaalta;
			}
			set
			{
				this._fechaalta = value;
			}
		}
		
		private DateTime? _fechabaja;
		public virtual DateTime? Fechabaja
		{
			get
			{
				return this._fechabaja;
			}
			set
			{
				this._fechabaja = value;
			}
		}
		
		private byte _correo;
		public virtual byte Correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				this._correo = value;
			}
		}
		
		private ushort _codiva;
		public virtual ushort Codiva
		{
			get
			{
				return this._codiva;
			}
			set
			{
				this._codiva = value;
			}
		}
		
		private byte _tipoirpf;
		public virtual byte Tipoirpf
		{
			get
			{
				return this._tipoirpf;
			}
			set
			{
				this._tipoirpf = value;
			}
		}
		
		private byte _tipoprod;
		public virtual byte Tipoprod
		{
			get
			{
				return this._tipoprod;
			}
			set
			{
				this._tipoprod = value;
			}
		}
		
		private ushort _codsitua;
		public virtual ushort Codsitua
		{
			get
			{
				return this._codsitua;
			}
			set
			{
				this._codsitua = value;
			}
		}
		
		private byte _tiporelacion;
		public virtual byte Tiporelacion
		{
			get
			{
				return this._tiporelacion;
			}
			set
			{
				this._tiporelacion = value;
			}
		}
		
		private string _dirsociocorreo;
		public virtual string Dirsociocorreo
		{
			get
			{
				return this._dirsociocorreo;
			}
			set
			{
				this._dirsociocorreo = value;
			}
		}
		
		private string _pobsociocorreo;
		public virtual string Pobsociocorreo
		{
			get
			{
				return this._pobsociocorreo;
			}
			set
			{
				this._pobsociocorreo = value;
			}
		}
		
		private string _prosociocorreo;
		public virtual string Prosociocorreo
		{
			get
			{
				return this._prosociocorreo;
			}
			set
			{
				this._prosociocorreo = value;
			}
		}
		
		private string _codpostalcorreo;
		public virtual string Codpostalcorreo
		{
			get
			{
				return this._codpostalcorreo;
			}
			set
			{
				this._codpostalcorreo = value;
			}
		}
		
		private short _esfactadvinterna;
		public virtual short Esfactadvinterna
		{
			get
			{
				return this._esfactadvinterna;
			}
			set
			{
				this._esfactadvinterna = value;
			}
		}
		
		private string _codigoggap;
		public virtual string Codigoggap
		{
			get
			{
				return this._codigoggap;
			}
			set
			{
				this._codigoggap = value;
			}
		}
		
		private short _emitefact;
		public virtual short Emitefact
		{
			get
			{
				return this._emitefact;
			}
			set
			{
				this._emitefact = value;
			}
		}
		
		private IList<Rfactsoc> _rfactsocs = new List<Rfactsoc>();
		public virtual IList<Rfactsoc> Rfactsocs
		{
			get
			{
				return this._rfactsocs;
			}
		}
		
		private IList<Rcampo> _rcampos = new List<Rcampo>();
		public virtual IList<Rcampo> Rcampos
		{
			get
			{
				return this._rcampos;
			}
		}
		
		private IList<Rcampo> _rcampos1 = new List<Rcampo>();
		public virtual IList<Rcampo> Rcampos1
		{
			get
			{
				return this._rcampos1;
			}
		}
		
	}
}
#pragma warning restore 1591
