#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace AriAgroModel	
{
	public partial class Variedade
	{
		private uint _codvarie;
		public virtual uint Codvarie
		{
			get
			{
				return this._codvarie;
			}
			set
			{
				this._codvarie = value;
			}
		}
		
		private string _nomvarie;
		public virtual string Nomvarie
		{
			get
			{
				return this._nomvarie;
			}
			set
			{
				this._nomvarie = value;
			}
		}
		
		private ushort _codprodu;
		public virtual ushort Codprodu
		{
			get
			{
				return this._codprodu;
			}
			set
			{
				this._codprodu = value;
			}
		}
		
		private ushort _codclase;
		public virtual ushort Codclase
		{
			get
			{
				return this._codclase;
			}
			set
			{
				this._codclase = value;
			}
		}
		
		private int _codconse;
		public virtual int Codconse
		{
			get
			{
				return this._codconse;
			}
			set
			{
				this._codconse = value;
			}
		}
		
		private decimal? _kgscajon;
		public virtual decimal? Kgscajon
		{
			get
			{
				return this._kgscajon;
			}
			set
			{
				this._kgscajon = value;
			}
		}
		
		private decimal? _minkgcaj;
		public virtual decimal? Minkgcaj
		{
			get
			{
				return this._minkgcaj;
			}
			set
			{
				this._minkgcaj = value;
			}
		}
		
		private decimal? _maxkgcaj;
		public virtual decimal? Maxkgcaj
		{
			get
			{
				return this._maxkgcaj;
			}
			set
			{
				this._maxkgcaj = value;
			}
		}
		
		private decimal? _facorrde;
		public virtual decimal? Facorrde
		{
			get
			{
				return this._facorrde;
			}
			set
			{
				this._facorrde = value;
			}
		}
		
		private decimal? _facorrme;
		public virtual decimal? Facorrme
		{
			get
			{
				return this._facorrme;
			}
			set
			{
				this._facorrme = value;
			}
		}
		
		private decimal? _arrobjor;
		public virtual decimal? Arrobjor
		{
			get
			{
				return this._arrobjor;
			}
			set
			{
				this._arrobjor = value;
			}
		}
		
		private decimal? _porcindu;
		public virtual decimal? Porcindu
		{
			get
			{
				return this._porcindu;
			}
			set
			{
				this._porcindu = value;
			}
		}
		
		private decimal? _porcmerm;
		public virtual decimal? Porcmerm
		{
			get
			{
				return this._porcmerm;
			}
			set
			{
				this._porcmerm = value;
			}
		}
		
		private decimal? _porcdest;
		public virtual decimal? Porcdest
		{
			get
			{
				return this._porcdest;
			}
			set
			{
				this._porcdest = value;
			}
		}
		
		private decimal? _eurdesta;
		public virtual decimal? Eurdesta
		{
			get
			{
				return this._eurdesta;
			}
			set
			{
				this._eurdesta = value;
			}
		}
		
		private decimal? _eurecole;
		public virtual decimal? Eurecole
		{
			get
			{
				return this._eurecole;
			}
			set
			{
				this._eurecole = value;
			}
		}
		
		private decimal? _eurmanob;
		public virtual decimal? Eurmanob
		{
			get
			{
				return this._eurmanob;
			}
			set
			{
				this._eurmanob = value;
			}
		}
		
		private decimal? _eursegsoc;
		public virtual decimal? Eursegsoc
		{
			get
			{
				return this._eursegsoc;
			}
			set
			{
				this._eursegsoc = value;
			}
		}
		
		private decimal? _eurotria;
		public virtual decimal? Eurotria
		{
			get
			{
				return this._eurotria;
			}
			set
			{
				this._eurotria = value;
			}
		}
		
		private decimal? _eurhaneg;
		public virtual decimal? Eurhaneg
		{
			get
			{
				return this._eurhaneg;
			}
			set
			{
				this._eurhaneg = value;
			}
		}
		
		private ushort? _codunida;
		public virtual ushort? Codunida
		{
			get
			{
				return this._codunida;
			}
			set
			{
				this._codunida = value;
			}
		}
		
		private string _ctavtasinterior;
		public virtual string Ctavtasinterior
		{
			get
			{
				return this._ctavtasinterior;
			}
			set
			{
				this._ctavtasinterior = value;
			}
		}
		
		private string _ctavtasexportacion;
		public virtual string Ctavtasexportacion
		{
			get
			{
				return this._ctavtasexportacion;
			}
			set
			{
				this._ctavtasexportacion = value;
			}
		}
		
		private string _ctavtasindustria;
		public virtual string Ctavtasindustria
		{
			get
			{
				return this._ctavtasindustria;
			}
			set
			{
				this._ctavtasindustria = value;
			}
		}
		
		private string _ctavtasretirada;
		public virtual string Ctavtasretirada
		{
			get
			{
				return this._ctavtasretirada;
			}
			set
			{
				this._ctavtasretirada = value;
			}
		}
		
		private string _ctavtasotros;
		public virtual string Ctavtasotros
		{
			get
			{
				return this._ctavtasotros;
			}
			set
			{
				this._ctavtasotros = value;
			}
		}
		
		private byte _codigiva;
		public virtual byte Codigiva
		{
			get
			{
				return this._codigiva;
			}
			set
			{
				this._codigiva = value;
			}
		}
		
		private string _codccost;
		public virtual string Codccost
		{
			get
			{
				return this._codccost;
			}
			set
			{
				this._codccost = value;
			}
		}
		
		private string _ctatrainterior;
		public virtual string Ctatrainterior
		{
			get
			{
				return this._ctatrainterior;
			}
			set
			{
				this._ctatrainterior = value;
			}
		}
		
		private string _ctatraexporta;
		public virtual string Ctatraexporta
		{
			get
			{
				return this._ctatraexporta;
			}
			set
			{
				this._ctatraexporta = value;
			}
		}
		
		private byte _tipoclasifica;
		public virtual byte Tipoclasifica
		{
			get
			{
				return this._tipoclasifica;
			}
			set
			{
				this._tipoclasifica = value;
			}
		}
		
		private int? _rdtomaximo;
		public virtual int? Rdtomaximo
		{
			get
			{
				return this._rdtomaximo;
			}
			set
			{
				this._rdtomaximo = value;
			}
		}
		
		private string _ctaanticipo;
		public virtual string Ctaanticipo
		{
			get
			{
				return this._ctaanticipo;
			}
			set
			{
				this._ctaanticipo = value;
			}
		}
		
		private string _ctaliquidacion;
		public virtual string Ctaliquidacion
		{
			get
			{
				return this._ctaliquidacion;
			}
			set
			{
				this._ctaliquidacion = value;
			}
		}
		
		private string _ctacomtercero;
		public virtual string Ctacomtercero
		{
			get
			{
				return this._ctacomtercero;
			}
			set
			{
				this._ctacomtercero = value;
			}
		}
		
		private string _ctacomisionista;
		public virtual string Ctacomisionista
		{
			get
			{
				return this._ctacomisionista;
			}
			set
			{
				this._ctacomisionista = value;
			}
		}
		
		private string _ctasiniestros;
		public virtual string Ctasiniestros
		{
			get
			{
				return this._ctasiniestros;
			}
			set
			{
				this._ctasiniestros = value;
			}
		}
		
		private string _ctatransporte;
		public virtual string Ctatransporte
		{
			get
			{
				return this._ctatransporte;
			}
			set
			{
				this._ctatransporte = value;
			}
		}
		
		private string _ctaacarecol;
		public virtual string Ctaacarecol
		{
			get
			{
				return this._ctaacarecol;
			}
			set
			{
				this._ctaacarecol = value;
			}
		}
		
		private short _tipovariedad;
		public virtual short Tipovariedad
		{
			get
			{
				return this._tipovariedad;
			}
			set
			{
				this._tipovariedad = value;
			}
		}
		
		private short _tipovarie2;
		public virtual short Tipovarie2
		{
			get
			{
				return this._tipovarie2;
			}
			set
			{
				this._tipovarie2 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
